### PR TITLE
Make endings of HTTP errors more consistent

### PR DESCRIPTION
**Pull request by bhrutledge**
I noticed these when writing up https://github.com/pypa/twine/issues/587

- Add missing periods
- Use "for more information" on all URLs (since it seemed to be the more common pattern)

### CODE REVIEW

**Comment by bhrutledge** [comment]
Ah, I was wondering if this would break the tests. I haven't set up a full development environment yet. Before I do that, I'm wondering how likely this is to get merged. @di @ewdurbin any thoughts?

**Comment by di** [comment]
@bhrutledge Sure, I'd merge this.

**Comment by di** [comment]
@bhrutledge Still planning to update the tests here or should I close for now?

**Comment by bhrutledge** [comment]
@di Hoping to do this, since https://github.com/pypa/twine/pull/666 put it back on radar. Maybe this weekend?

**Comment by bhrutledge** [comment]
@di The checks are passing. Thanks for the nudge.

**Comment by di** [comment]
Thanks!

**Pull request merged**
