### PR TITLE
Remove placeholder text for deletion confirmation model

### PR DESCRIPTION
**Pull request by venthur**
Fixes the placeholder issues and the case of "Project Name" the confirmation of the file deletion via project name will be fixed through #3163

### CODE REVIEW

**Comment by brainwane** [comment]
Thanks for the PR, @venthur! @aalmazan could I ask you to look at this?

**Comment by aalmazan** [comment]
@brainwane Took a look and the first commit looks good. The second, however, may be introducing something unintended? I'm not sure what's expected, but that change will also change behavior in, for example, the delete file confirmation modal.

`fix/3162` now matches @nlhkabu 's [suggested example](https://github.com/pypa/warehouse/issues/3163#issuecomment-375195865), but I'm not sure if the removal of the placeholder was intentional. 

selection_030

vs. the current version on #3378 

selection_029

**Comment by nlhkabu** [comment]
Yes, @aalmazan the removal of the placeholder is intentional.  We had feedback from user testing that this was confusing (some users didn't realise it was a placeholder - they thought it was real text).  I am happy to merge this if you are :)

**Comment by aalmazan** [comment]
@nlhkabu Sorry about the delay (and I see it's already been merged haha), but no objections from me :+1:

**Comment by brainwane** [comment]
@venthur Thanks for the fix! Let me know if you'd like a suggestion for another issue to work on?

**Pull request merged**
