### PR TITLE
Add temporary login page

### LINKED ISSUE #1316: Add temporary login page, replace login and register links
As we will not be launching with anything meaningful to do in the logged in section, I think we should create a 'temporary login' page that:

- Has a large button redirecting back to the old PyPI
- Explains that the logged in features are on our 'todo' list and will be done soon
- Invites users to contribute to the project
- Asks for donations

Something like (with links added):

"We're currently working on making the logged in pages on PyPI better.  If you'd like to see this happen sooner, please consider contributing to Warehouse, or making a donation (or asking your company to make a donation) towards the ongoing development of the Warehouse project"

We could host this at `/temp-login/' and replace the current login and register links with a link to this page.

### PR DESCRIPTION
**Pull request by berkerpeksag**
Closes #1316

This feels a little bit hacky, but please let me know if there is a better way to do this.

### CODE REVIEW

**Comment by di** [comment]
Hi @berkerpeksag, thanks for taking care of this!

I think we probably don't need the redirects and passed tests -- it should suffice to replace the form in `register.html` the same way you did in `login.html`. You also might want to use a Jinja macro to do this so the copy is not repeated in both templates.

Instead of the redirect, we should do what @nlhkabu said in #1432, and add a large button which will lead to the original PyPI when clicked. Something like:

```html
<a class="button button--large button--dark" href="https://pypi.python.org/pypi?%3Aaction=login_form">Login at pypi.python.org</a>
```

for the login page, and something similar for the register page.

**Comment by berkerpeksag** [comment]
Ok, for some reason I can get coverage.py to work with `# pragma: no cover` and `# pragma: no branch`.

Thanks for the review, @di. I've addressed all of your review comments.

**Comment by di** [comment]
@berkerpeksag If we hide the forms with a `display: none` instead of commenting them out, we can leave all the tests as-is (except for `test_templates_for_empty_titles`) and coverage should remain at 100%.

I'm not sure if this would need to be inlined to prevent the form briefly appearing before the stylesheets are applied, or if it could live in `_forms.scss` -- perhaps @nlhkabu can let us know.

Here's a screenshot for everyone else:

screen shot 2016-08-23 at 10 27 35 am

**Comment by berkerpeksag** [comment]
> @berkerpeksag If we hide the forms with a display: none instead of commenting them out, we can leave all the tests as-is

Right, but wouldn't that make login and register available to some curious users?

**Comment by dstufft** [comment]
I'm not really worried about people going out of their way to log into Warehouse. There's no harm in allowing it other than it's kind of confusing to log into Warehouse and then be unable to actually *do* anything.

**Comment by berkerpeksag** [comment]
Wouldn't be better to set coverage target to 99% for now? :)

**Comment by dstufft** [comment]
> Wouldn't be better to set coverage target to 99% for now? :)

I don't think so! The 100% limit ensures things get covered, if we lower it, then other things can accidentally get committed that don't have coverage as well.

**Comment by berkerpeksag** [comment]
Ok, fair enough. I'll let someone else finish this up.

**Pull request closed without merging**
