### PR TITLE
Revert "Refactoring multiple parts of the dockerfile (#10004)"

### PR DESCRIPTION
**Pull request by di**
This reverts commit 6581b0225686270140415b35dfdaa4a00da15674.

### CODE REVIEW

**Review by ewdurbin — APPROVED** [review]

**Comment by abitrolly** [comment]
Why?

**Comment by ewjoachim** [comment]
Because it broke the deployment pipeline, most likely due to Buildkit not being currently supported. https://github.com/pypa/warehouse/pull/10021#issuecomment-915383386

**Comment by abitrolly** [comment]
Are there any public builds logs or issues to see what went wrong during deployment?

I haven't found any reference to BuildKit in this project. Docker [docs](https://docs.docker.com/develop/develop-images/build_enhancements/#to-enable-buildkit-builds) say the BuildKit needs to be explicitly enabled, so why did it kick in?

**Comment by ewjoachim** [comment]
I'm not sure but I don't think this part of the deployment is public.

**Pull request merged**
