### PR TITLE
Add mirror html template

### PR DESCRIPTION
**Pull request by nlhkabu**
ping @ewdurbin

### CODE REVIEW

**Comment by ewdurbin** [comment]
@nlhkabu all yours now :)

**Comment by nlhkabu** [comment]
Just reviewed the page, it looks fine as is :)
@ewdurbin I notice that the timezone isn't loading again?

**Comment by ewdurbin** [comment]
Time stamp will only load on a mirror, as it requires the last-updated file to exist.

**Comment by nlhkabu** [comment]
@ewdurbin I assume this needs to be a full stand-alone HTML page (not using the base template)?  The CI failures all seem to relate to the fact that this is not a standard Jinja template (inline CSS, no blocks, etc.). Do you have any advice on how to get around this?

**Comment by ewdurbin** [comment]
@nlhkabu could it be as simple as moving the static page into `warehouse/static/html/mirror.html`?

**Pull request merged**
