### PR TITLE
Fix the spelling of the word 'Library'

### PR DESCRIPTION
**Pull request by alexwlchan**

### CODE REVIEW

**Comment by ewdurbin** [comment]
thank you, @alexwlchan

**Comment by brainwane** [comment]
@alexwlchan Thanks for your PR! Would you be interested in a suggestion of another issue to address?

**Comment by alexwlchan** [comment]
@brainwane Sure, I can take a look!

**Comment by brainwane** [comment]
@alexwlchan Thanks! How about #3164?

**Pull request merged**
