### PR TITLE
Upgrade ES version to latest

### PR DESCRIPTION
**Pull request by di**
An alternative to #1037

(Closes #1037)

### CODE REVIEW

**Comment by dstufft** [comment]
This should probably pin to at least ``2`` explicitly, if not ``2.2``.

**Comment by dstufft** [comment]
(For the record, 2.2.1 is what we're using in production right now for Warehouse)

**Comment by di** [comment]
@dstufft I amended it to pin to `2.2`, would you prefer `2.2.1`?

**Comment by dstufft** [comment]
Nah, ``2.2`` should be fine.

**Pull request merged**
