### PR TITLE
Add Brazilian Portuguese support

### LINKED ISSUE #6744: Add Brazilian Portugese to localization footer
https://hosted.weblate.org/projects/pypa/warehouse/#translations says that we're now at 100% translated for Brazilian Portugese. Therefore, let's insert the footer of available locales/translations per #6624, and add Brazilian Portugese.

@yeraydiazdiaz @nlhkabu can either of you do this? Thanks.

### PR DESCRIPTION
**Pull request by brainwane**
We now have 100% string translation for Brazilian
Portugese via Weblate.

Fixes #6744.

### CODE REVIEW

**Comment by brainwane** [comment]
I assume this is blocked on merging at least part of #6667.

**Comment by woodruffw** [comment]
This should be good to go!

N.B: To test these changes locally, run `make build-mos` to compile the `.po`s into their respective `.mo`s.

**Comment by brainwane** [comment]
Thanks @woodruffw for the instructions! I currently can't follow them because of a problem on master (#6778). If you could share a screenshot here, that'd really help me with my report.

**Comment by woodruffw** [comment]
> If you could share a screenshot here, that'd really help me with my report.

Sure, I can do that this evening if that works for you.

**Comment by brainwane** [comment]
Great - as long as I don't already have my locale cookie set, this seems to work locally!

pypi-in-portugese

Should we merge this to master?

**Pull request merged**
