### PR TITLE
Create rate_limits doc

### PR DESCRIPTION
**Pull request by samgdf**
Add rate_limits doc

### CODE REVIEW

**Comment by brainwane** [comment]
And @samgdf, if you are working on this PR and have questions, please feel free to ask them here, in [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or on the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by brainwane** [comment]
@samgdf Sorry I missed you while you were in IRC. Thanks for offering to rewrite in `.rst`! And I'll defer to Dustin on this being more developer-centric documentation rather than API user help.

You asked,

> on the issue of rate-limits for API's, doesn't it just vary by API? Or should I use a standardized 100/1000/10000?

@ewdurbin may have insight here too.

**Comment by brainwane** [comment]
@samgdf ping - will you be working on this in the next few weeks? Thanks!

**Comment by di** [comment]
Closing this due to inactivity.

**Comment by brainwane** [comment]
@samgdf Thanks for giving this a try, and if you'll be at [the PyCon or EuroPython sprints](https://wiki.python.org/psf/PackagingSprints) we'd be happy to set you up with a different issue to fix!

**Pull request closed without merging**
