### PR TITLE
Add PyPI Notifier to release notification services

### PR DESCRIPTION
**Pull request by cenkalti**
https://github.com/cenkalti/pypi-notifier/issues/8

### CODE REVIEW

**Comment by malikoth** [comment]
Looks good, recommend to merge @brainwane

**Comment by greysteil** [comment]
Yeah, I agree with that - seems odd for you to be curating this list.

The only place with an organisation curating this that I'm aware of is the dependency management section of the GitHub Marketplace, [filtered for Python](https://github.com/marketplace/category/dependency-management?utf8=%E2%9C%93&query=python). The downside is that that doesn't (yet) have pyup.io on it, but the upside is it would shift these requests to GitHub and away from PyPI.

**Comment by greysteil** [comment]
Oops, meant to comment on #3907!

**Comment by di** [comment]
No worries, we can consolidate communication on this thread!

**Comment by greysteil** [comment]
👍 - have closed my PR.

So my recommendation here would be to update the text to read:

> PyPI itself does not offer a way to get notified when a project uploads new releases. However, there are several third-party services that offer comprehensive monitoring and notifications for project releases and vulnerabilities listed as [GitHub apps](https://github.com/works-with/category/dependency-management?utf8=%E2%9C%93&query=python).

**Pull request closed without merging**
