### PR TITLE
Show name as well as gravatar on project detail page

### LINKED ISSUE #3005: show name, not only gravatar on project page
it only shows the gravatar icon in the maintainers section (in my case some meaningless standard icon as i do not use gravatar), see screenshot from borgbackup project.

screenshot from 2018-02-20 23-44-34

imho, it should display the name as text to the right of the icon.

### PR DESCRIPTION
**Pull request by jonparrott**
Fixes #3005 

This is my first time doing anything with the CSS here, so if I did something wrong please let me know!

Screenshot:

screen shot 2018-03-31 at 7 44 28 pm

/cc @nlhkabu

### CODE REVIEW

**Comment by pgadige** [comment]
The pull request branch successfully works for me. It also passes all the tests and is validated by `lint`. Thank you @jonparrott for the PR, and @brainwane for helping me with my first pull request testing.

**Comment by nlhkabu** [comment]
hi @jonparrott thanks for this PR

Unfortunately, this does not wrap as expected on tablet:

screenshot from 2018-04-03 06-52-13

To get around this, we can apply the styles to each maintainer with `sidebar-section__maintainer`

```html
<div class="sidebar-section">
  <h3 class="sidebar-section__title">Maintainers</h3>
  {% for maintainer in maintainers %}
    {% set alt = "Avatar for {} from gravatar.com".format(maintainer.username) %}
    <span class="sidebar-section__maintainer">
      <a href="{{ request.route_path('accounts.profile', username=maintainer.username) }}" aria-label="{{ maintainer.username}}" class="sidebar-section__user-gravatar">
        <img src="{{ gravatar(maintainer.email, size=50) }}" height="50" width="50" alt="{{ alt }}" title="{{ alt }}">
      </a>
      <a href="{{ request.route_path('accounts.profile', username=maintainer.username) }}">
        {{ maintainer.username}}
      </a>
    </span>
  {% endfor %}
</div>
```
In the CSS, we can then use flexbox to align each item.  We add `word-break: break-word;` to wrap any long names.

```css
&__maintainer {
  display: flex;
  align-items: center;

  a {
    margin-bottom: 5px;
    word-break: break-word;
  }

  img {
    margin-right: 10px;
    
    @media only screen and (max-width: $desktop) {
      max-width: 40px;
      max-height: 40px;
    }
  }
}
```

This works on both desktop and tablet:

screenshot from 2018-04-03 07-02-15

screenshot from 2018-04-03 07-01-12

Note that I also removed the `<strong>` style, as we're not using it anywhere else on links in the sidebar :)

**Comment by nlhkabu** [comment]
Note, this PR will need to be tested in ie11

**Comment by nlhkabu** [comment]
great! Thanks @jonparrott!

**Comment by jonparrott** [comment]
@nlhkabu suggestions added, seems to work as expected on desktop and tablet. I don't have ie11 handy right now, but could test this weekend.

**Comment by nlhkabu** [comment]
Thanks for the update @jonparrott!

Just tested on ie11 and it looks as though `break-word` isn't taking effect:

screenshot from 2018-04-07 07-07-20

Perhaps adding `word-break: break-word;` will help?  Ref: https://stackoverflow.com/questions/34532242/how-to-mimic-word-break-break-word-for-ie9-ie11-and-firefox

Could you also please remove the bold style?  We don't have bold links anywhere else in the sidebar, so it would be better to remove this for consistency :)

**Comment by jonparrott** [comment]
@nlhkabu I tried various things but could not get this to work properly in IE11/Firefox.

**Comment by nlhkabu** [comment]
Ok, thanks @jonparrott.  Let me take a second look and see if I can get it to work...

**Comment by jonparrott** [comment]
@nlhkabu thanks for helping with this. I've pushed your recommendation up and tested with Chrome and FF. If you could verify with IE that would be awesome.

**Comment by jonparrott** [comment]
Yay, thanks for everything @nlhkabu!

**Comment by nlhkabu** [comment]
:tada:

**Pull request merged**
