### PR TITLE
Replace TODOs with PyPUG links in homepage

### LINKED ISSUE #1301: Two links in homepage intro text should link to PyPUG guides
Learn about installing packages: https://packaging.python.org/installing/
Learn how to package your Python code for PyPI: https://packaging.python.org/distributing/

### PR DESCRIPTION
**Pull request by berkerpeksag**
Fixes #1301

### CODE REVIEW

**Comment by alex** [comment]
I don't understand the errors coming out of the HTML lint at all.

**Comment by nlhkabu** [comment]
The linter enforces the [Google HTML style guide](https://google.github.io/styleguide/htmlcssguide.xml)

It looks like it's objecting to a couple of things:

Links should not have protocols, so `<a href="https://packaging.python.org/installing/">` should turn into `<a href="//packaging.python.org/installing/"`

The other is a finicky indentation error, I'm pretty sure it will be fixed if you put the content all on one row, e.g:

```
<p>PyPI helps you find and install third-party software developed and shared by other members of the Python community. <a href="https://packaging.python.org/installing/">Learn about installing packages</a>.</p>
```

Sorry, I should have mentioned the HTML linting rules when I created the issue.

**Comment by alex** [comment]
Using `//packaging.python.org` seems strictly worse, we want to link to an
HTTPS site regardless of what protocol we're using to serve this page (it's
always HTTPS in production, but during local dev it might be HTTP)

On Sat, Jul 2, 2016 at 12:05 PM, Nicole Harris <notifications@github.com>
wrote:

> The linter enforces the Google HTML style guide
> <https://google.github.io/styleguide/htmlcssguide.xml>
>
> It looks like it's objecting to a couple of things:
>
> Links should not have protocols, so <a href="
> https://packaging.python.org/installing/"> should turn into <a href="//
> packaging.python.org/installing/"
>
> The other is a finicky indentation error, I'm pretty sure it will be fixed
> if you put the content all on one row, e.g:
>
> <p>PyPI helps you find and install third-party software developed and shared by other members of the Python community. <a href="https://packaging.python.org/installing/">Learn about installing packages</a>.</p>
>
> Sorry, I should have mentioned the HTML linting rules when I created the
> issue.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pypa/warehouse/pull/1339#issuecomment-230109020>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAADBO0na5K1bFQUZANB9JnsY_k2ud7Gks5qRoxUgaJpZM4JDsSD>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: D1B3 ADC0 E023 8CA6

**Comment by nlhkabu** [comment]
In which case we need to reasses this rule. I'll open a new issue.

**Comment by nlhkabu** [comment]
In the short term @berkerpeksag - if you update the indentation, I should be able to merge this, as the protocol thing is only a warning.

**Comment by berkerpeksag** [comment]
Apparently `html-linter` returns non-zero for warnings too:

```sh
$ html_lint.py --disable=optional_tag,names `find ./warehouse/templates -path ./warehouse/templates/legacy -prune -o -name '*.html' -print`
64:18: Warning: Protocol: Do not specify the protocol unless required: Remove the protocol "https:" from the url.
68:18: Warning: Protocol: Do not specify the protocol unless required: Remove the protocol "https:" from the url.
$ echo $?
```

**Comment by nlhkabu** [comment]
Ok, sorry @berkerpeksag - I'll prioritise updating the linter and rerun this once it's sorted.  Thanks for the PR :)

**Comment by dstufft** [comment]
✨

**Comment by nlhkabu** [comment]
thanks @berkerpeksag and thanks for sorting the linter @dstufft :) 

:tada: :dancers:

**Pull request merged**
