### PR TITLE
Add shorthands for `/user` and `/simple`

### PR DESCRIPTION
**Pull request by tusharsadhwani**
Inspired by the `/p` shorthand for the `/project` endpoint.

### CODE REVIEW

**Comment by di** [comment]
Thanks! I've been meaning to add `/u` for ages. Could you update the tests as well?

**Comment by tusharsadhwani** [comment]
@di I would, if I hadn't painfully made this PR from my phone. I'll do this when I wake up tomorrow :)

**Review by ewjoachim — APPROVED** [review]

**Comment by ewdurbin** [comment]
Ran across this when researching another issue. I'm not a huge fan of this for "API" endpoints like the `/s/` for `/simple/`, and even less so as a blind redirect that won't be cached at the edge.

@di thoughts on removing this? In a cursory overview it doesn't appear to be in regular use, and I'd like to remove it before it happens to.

**Comment by tusharsadhwani** [comment]
If /u is staying, I'm completely fine with it too

**Comment by di** [comment]
Agreed.

**Pull request merged**
