### PR TITLE
Change icon for changelog links -> Corrected #8089

### LINKED ISSUE #8089: Change icon for changelog / history ?
On the package detail page, we currently show the "gift" icon for the following words:
"changelog", "change log", "changes", "release notes", "news", "what's new", "history"

e.g.

Screenshot from 2020-06-10 22-01-39

Maybe this is not the best icon?
see https://github.com/pypa/warehouse/pull/7896#issuecomment-624788423

Maybe we should choose a different fontawesome icon?

---

**Screenshot Required**: This issue will require an update to the visual design of the site. To help our team give you faster feedback, include a screenshot in your Pull Request.

### PR DESCRIPTION
**Pull request by boringow**
Changed the changelog icon gift to scroll

Fixes #8089.

### CODE REVIEW

**Comment by pradyunsg** [comment]
Related to #8089

**Comment by merwok** [comment]
A minor point: titles in PRs are most useful if they say what the change is!  Here for example `Change icon for changelog links`.

**Comment by boringow** [comment]
@merwok thanks! I am new into github and I am learning the rules and how to do pull requests and other stuff, I will keep it in mind for further ocasions 👍🏽

**Comment by merwok** [comment]
Do you mind editing this one too?

**Comment by boringow** [comment]
done :)

**Pull request merged**
