### PR TITLE
Enable uk locale

### PR DESCRIPTION
**Pull request by webknjaz**
(probably needs weblate contents to be synced to Git first)

### CODE REVIEW

**Comment by webknjaz** [comment]
@ewdurbin @di this should be ok to merge since #6821 is in master.

**Comment by di** [comment]
@webknjaz This also needs the compiled MO file, see the instructions at https://warehouse.readthedocs.io/translations/#adding-a-newly-completed-translation

**Comment by webknjaz** [comment]
@di done

**Comment by webknjaz** [comment]
@di anything else?

**Comment by ewdurbin** [comment]
thank you @webknjaz !

**Comment by webknjaz** [comment]
Thanks, Ernest!

**Pull request merged**
