### PR TITLE
Expose requires-python metadata

### LINKED ISSUE #1324: Expose 'requires-python' metadata in package detail sidebar
From #1061 

> Adding requires-python would be good, probably something that can wait until after launch though because while I think it's a generally useful feature, I don't think anyone currently uses it (because setuptools doesn't expose it).

### PR DESCRIPTION
**Pull request by berkerpeksag**
Closes #1324

### CODE REVIEW

**Comment by nlhkabu** [comment]
Ok for me @dstufft :)

**Comment by berkerpeksag** [comment]
Thanks for the review, @nlhkabu. Let me know if you want me to fix the merge conflict.

**Comment by dstufft** [comment]
Sorry this fell through the cracks, if you fix the merge conflicts we can get this merged.

**Comment by berkerpeksag** [comment]
I forgot to fix the merge conflicts last week. It's now done. Thanks!

**Comment by dstufft** [comment]
Thanks!

**Pull request merged**
