### PR TITLE
Add controller for search focus for slash keypress

### LINKED ISSUE #6099: Create keyboard shortcut to focus search bar
**What's the problem this feature will solve?**
We have decided *not* to autofocus the search bar on the PyPI homepage (see #6088)

However, we should consider creating a keyboard shortcut to move users to the search bar.

**Describe the solution you'd like**
The solution should be:

- Easy for PyPI users to discover
- Simple
- It should *not* interfere with keyboard shortcuts used by screenreader users (we need to research this)

**Additional context**
Suggestion from @amcgregor:

On YouTube typing `/` activates search, while typing `?` shows a shortcut reference.  See the [original comment](https://github.com/pypa/warehouse/issues/3440#issuecomment-505631589) for more info.

### PR DESCRIPTION
**Pull request by miketheman**
While having the search key autofocus is forbidden, having a keypress
focus the search field is a desirable feature.

Add a new Stimulus Controller that listens to the `/` keypress and
focuses the input on the search field.

Note: Currently applies only to the home page.

Fixes #6099

Signed-off-by: Mike Fiedler <miketheman@gmail.com>

### CODE REVIEW

**Comment by di** [comment]
Thanks! I think if we add a check that the cursor is not currently in an input field, we could add this to the base template, so this is usable everywhere the search box is currently present.

**Comment by miketheman** [comment]
Happy to look at that change as well - but then I'm not sure how the base template property would be inherited to the homepage's search box?

**Comment by di** [comment]
It wouldn't, we'd need to add it to both the form on the homepage (which you've already done here) and to this form: https://github.com/pypa/warehouse/blob/597938cff04261fd55f59dd538982b4bfcad4621/warehouse/templates/base.html#L225-L233

**Comment by miketheman** [comment]
@di I think I'm ready for another review! I'm happier with this implementation - it's more tightly scoped, albeit increasing the html line length.

**Review by di — APPROVED** [review]

**Comment by di** [comment]
Thanks, this is great!

**Pull request merged**
