### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/pypa/warehouse/) for pypa/warehouse.

### CODE REVIEW

**Comment by pradyunsg** [comment]
Q: how often should we be merging these updates? I default to unsubscribing from these PRs directly, but would it be helpful in any way to have more fingers click merge on Weblate PRs?

**Comment by di** [comment]
They can be merged whenever they exist, but I try to do it no more than 1x a week, otherwise they'd basically be generating a PR every day which gets very noisy.

**Comment by webknjaz** [comment]
@di it looks like merging the translations is not quite enough. I noticed that some of them don't show up on pypi.org.

For example, there's https://github.com/pypa/warehouse/blame/68adfd6/warehouse/locale/uk/LC_MESSAGES/messages.po#L5482 merged _4 months ago_ and https://pypi.org/help/#invalid-auth (same for https://test.pypi.org/help/#invalid-auth) still has the English version of that paragraph.

**Comment by di** [comment]
Looks like you're actually talking about these lines? https://github.com/pypa/warehouse/blame/68adfd6/warehouse/locale/uk/LC_MESSAGES/messages.po#L5339-L5346

That's fairly weird. I'm seeing it for other languages (like French) as well. I'll merge this and we'll see if that improves anything.

**Comment by di** [comment]
Looks like the issue is that Weblate is not building our `.mo` files for us in these PRs, and I'm not sure it ever did. https://github.com/pypa/warehouse/pull/8578 should resolve this.

**Comment by webknjaz** [comment]
> Looks like you're actually talking about these lines?

Not these specifically but I've seen many other occurrences of this problem too.

**Comment by di** [comment]
I've also enabled the ["Generate MO files" addon](https://docs.weblate.org/en/latest/admin/addons.html#generate-mo-files) which should do this automatically in future Weblate PRs for us.

**Pull request merged**
