### PR TITLE
Combined 11 Dependabot Pull requests

### PR DESCRIPTION
**Pull request by miketheman**
* Closes #11553
* Closes #11552
* Closes #11551
* Closes #11550
* Closes #11549
* Closes #11544
* Closes #11541
* Closes #11539
* Closes #11532
* Closes #11531

### CODE REVIEW

**Comment by di** [comment]
Not sure what's going on with the RTD build here.

**Comment by miketheman** [comment]
This looks similar to #11504 (blocked)

**Comment by miketheman** [comment]
I removed the changes to docs.txt to see if that gets past it for now, and we can revisit docs later.

**Comment by miketheman** [comment]
@di that seems to have done the trick!

**Pull request merged**
