### PR TITLE
add support for opengraph tags to warehouse

### LINKED ISSUE #677: Handle pinning on Pinterest
See https://bitbucket.org/pypa/pypi/issues/336/python-package-pages-pin-poorly-on

> @audreyr wrote:
> For example, when I try to pin Cookiecutter 1.0.0 on Pinterest:
> * it pins as "pypi.python.org" with no mention of the package name or version
> * the image doesn't get picked up.
> * the default text image should be the package name, not PYPI PYTHON ORG
> 3811756009-screen shot 2015-09-09 at 9 37 24 pm
> Feel free to close this out if it's too low-priority. I just figured you might want to know and have it tracked, since a lot of people (esp women) use Pinterest for all their bookmarking.

### PR DESCRIPTION
**Pull request by reaperhulk**
These tags are used for Facebook, Slack, Pinterest, and other sites and provide richer metadata when sharing links.

This may resolve #677.

### CODE REVIEW

**Comment by dstufft** [comment]
This looks good to me, but you'll need to fix the linting issues.

**Comment by reaperhulk** [comment]
PR updated. For some reason it's still failing with `17:1: Error: Encoding: The meta charset should be set to utf-8: Add the tag <meta charset="utf-8">.` even though that tag is present already (line 17 of base.html)

**Comment by di** [comment]
@reaperhulk Unfortunately the linter is not very sophisticated and just looks at each `.html` file individually, it doesn't know that the tag has already been added in `base.html`, thus it fails when it sees `meta` tags in `detail.html`

You could fix it by adding another meta tag with the charset in `detail.html`, but I think it would be better to add a macro in `base.html` for generating the `opengraph_tags` block from a title and description, and then call that from `detail.html` instead.

**Comment by dstufft** [comment]
Huh, maybe we should just disable the ``<meta charset>`` rule? Something that only has to exist in one file probably isn't something we need to really lint for?

**Comment by di** [comment]
@dstufft That's a good idea.

@reaperhulk You can disable that specific check by adding `charset` to the `--disable` flag here: https://github.com/pypa/warehouse/blob/master/Makefile#L118

**Pull request merged**
