### PR TITLE
Remove /stats/ route.

### PR DESCRIPTION
**Pull request by ewdurbin**
The query has become too pathological to serve live. It likely needs to be refactored somehow.

### CODE REVIEW

**Comment by ewdurbin** [comment]
cc @cooperlees

**Comment by ewdurbin** [comment]
Will be opening an inverse "restore..." PR and filing an issue after this merges.

**Comment by cooperlees** [comment]
A once an hour or even daily run would be fine. I did suggest this originally. Happy to knock this out at the sprints.

Also, wouldn't it be nicer to just send back a static response stating we're looking to scale it rather than 404? But I guess the 404 temporarily works. This isn't an important API.

**Comment by ewdurbin** [comment]
@cooperlees I agree, but I don't have the bandwidth at the moment to make a pretty response. could you PR one after this lands?

**Comment by cooperlees** [comment]
See if I get time - I'm at F8 today. Tomorrow when flying to Cleveland I'll try.

**Pull request merged**
