### PR TITLE
Fix typo in help.html

### LINKED ISSUE #6204: Fix "appliation" typo in help page
The word "appliation" on https://pypi.org/help/ should be "application". To fix this, edit `warehouse/templates/pages/help.html`.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

### PR DESCRIPTION
**Pull request by serhii73**
Close #6204

### CODE REVIEW

**Comment by di** [comment]
Thanks!

**Comment by brainwane** [comment]
Thanks, @serhii73! If you'd like a suggestion for another issue to fix, please say so!

**Comment by serhii73** [comment]
You're welcome. @brainwane 
Do you have any chat where I can ask about other issues? Or better write in issue page?

**Comment by brainwane** [comment]
@serhii73 Many Warehouse developers, and developers of related tools, hang out in [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev) -- if you can join me there now, we can talk about other issues!

**Pull request merged**
