### PR TITLE
Need to use pip < 10 until pip-tools supports pip 10

### PR DESCRIPTION
**Pull request by dstufft**

### CODE REVIEW

**Comment by ewdurbin** [comment]
it is the shoemakers shoes going shoeless :-p

**Comment by dstufft** [comment]
pip-tools isn't something I wrote!

**Comment by ewdurbin** [comment]
all of the cool kids are using pip10, Donald.

**Comment by alex** [comment]
I think this can be reverted now that pip-tools 2.0 is out.

**Pull request merged**
