### PR TITLE
Add Discord to custom icons for `project_urls`

### PR DESCRIPTION
**Pull request by jack1142**
Matches `discordapp.com`, `discord.gg` and `discord.com` links.
Example:
image

The used icon:
https://fontawesome.com/icons/discord?style=brands

### CODE REVIEW

**Comment by di** [comment]
Thanks for the contribution! You'll need to update the translations to get the tests to pass here, see https://warehouse.readthedocs.io/development/submitting-patches/#translations

**Comment by jack1142** [comment]
I missed that during my quick look through the contributing guidelines, thanks :)

**Comment by jack1142** [comment]
Welp, looks like something went wrong...

**Comment by jack1142** [comment]
Yeah, I don't know what I did wrong at first but now it works 😄

**Comment by di** [comment]
Thanks!

**Pull request merged**
