### PR TITLE
Add user dropdown menu

### PR DESCRIPTION
**Pull request by nlhkabu**
## Logged out
screenshot from 2017-06-20 19-37-14

## Logged in

screenshot from 2017-06-20 19-37-39

### CODE REVIEW

**Comment by nlhkabu** [comment]
Closes #780

**Comment by dstufft** [comment]
Feel free to tell me I'm wrong, but it feels to me like the blue on blue makes it easy to "lose" the dropdown menu into the header image. Maybe a white border around the left/right/bottom would help distinguish it? I dunno, maybe it's fine too :)

**Comment by nlhkabu** [comment]
I did try a white background, but it didn't feel consistent / part of the menu.  I'll try a white border, or maybe it's just a case of increasing the shadow.

FYI, I've also removed the not-essential links (donate, help) on mobile:
screenshot from 2017-06-20 20-41-29

i think we need to leave a fair bit of room here, because eventually we'll be translating these and they might become quite long.

**Comment by nlhkabu** [comment]
screenshot from 2017-06-20 20-48-10

Subtle, but definitely better - thanks for the suggestion @dstufft :)

**Comment by dstufft** [comment]
Yea, that stands out more as a separate entity and I don't feel like my eyes are getting lost. 💯

**Pull request merged**
