### PR TITLE
Approve organization account

### LINKED ISSUE #11087: Approve account
Feature request for organization account project in PyPI.

Description | PyPI Admin approves organization account
-- | --
User value | PyPI Admin ensures that there is no spurious use of an Organization’s name. PyPI Admin can control the number of accounts being created.
Acceptance criteria | Email notification to owners and PyPI Admin

### LINKED ISSUE #11287: List pending organization requests
As @ewdurbin described in #11208, in addition to notification emails, we want administrators to have a list of pending organization requests to approve/decline.

### PR DESCRIPTION
**Pull request by divbzero**
- Add new organization list page for administrators.
- Add new organization detail page for administrators.
- Add form to approve/decline organization to organization detail page.
- Record events for new organization approve/decline.
- Send emails to user and admins for new organization approve/decline.
- Closes #11087.
- Closes #11287.

**Testing Setup**

1. `make serve` to run locally.
2. `make initdb` to initialize database.
3. Uncheck and save the `disable-organizations` admin flag at http://localhost/admin/flags/.
4. Submit the **Create new organization** form at http://localhost/manage/organizations/.
5. Open the request notification email to admins using the maildev interface at http://localhost:1080/.

**Testing Steps**

1. Follow the approval link from the notification email to open the organization detail page.
2. Alternatively, open the detail page from the list page at http://localhost/admin/organizations/.
3. Click **Approve**/**Decline** and follow prompts to approve/decline the new organization.

**Expected Behavior**

1. Approve/decline fails if the confirmation prompts are not followed.
2. Organization approval page indicates when organization is approved/declined.
4. Approval notification emails to admins and the requesting user appear in the maildev interface at http://localhost:1080/.

### CODE REVIEW

**Comment by divbzero** [comment]
@ewdurbin This pull request is fully working and tested and is ready for review as soon as we merge #11184.

**Comment by divbzero** [comment]
Rebased against `main` to incorporate recent changes:
- #8324
- #11184

Events now use `Organization.Event` and record `user.id` for additional data.

**Comment by divbzero** [comment]
Rebased against `main` to include all changes since #11184.

**Review by ewdurbin — APPROVED** [review]
One request, but it can be addressed later. @s-mm can we ensure we capture the requested feature (list view for organization requests) somewhere?

**Comment by ewdurbin** [comment]
@divbzero if you don't respond saying "oh that's easy I'll add the list admin view real quick" I'll merge this later today.

**Comment by ewdurbin** [comment]
Thank you so much @divbzero

**Comment by ewdurbin** [comment]
It looks like a test is broken after rebase, or may be flaky.

**Pull request merged**
