### PR TITLE
Comment out project dependencies tab

### PR DESCRIPTION
**Pull request by TheJJ100100**
Commented out project dependencies tab for issue https://github.com/pypa/warehouse/issues/1309

### CODE REVIEW

**Comment by dstufft** [comment]
I think this is probably fine, but @nlhkabu might want to take a look to make sure!

**Comment by nlhkabu** [comment]
Thanks for the PR @TheJJ100100 

Can we please use Jinja2 block comments rather than HTML comments - this will prevent it from rendering in the HTML source.

**Comment by berkerpeksag** [comment]
Another option would be to use the `{# ... #}` syntax.

**Comment by TheJJ100100** [comment]
@nlhkabu Is this correct? @nlhkabu https://github.com/pypa/warehouse/pull/1346/commits/89175c76c575cfe27b9d2bff2f4f75126ddf511a

**Comment by nlhkabu** [comment]
Looks good to me @TheJJ100100 - assuming all checks pass this is ready to merge :)

**Comment by TheJJ100100** [comment]
Looks like this

**Comment by nlhkabu** [comment]
:tada: Thanks @TheJJ100100

**Comment by TheJJ100100** [comment]
Thanks @nlhkabu

**Pull request merged**
