### PR TITLE
Travis CI: Upgrade testing from Python 3.6 --> 3.7

### PR DESCRIPTION
**Pull request by cclauss**
The [Travis CI worker continues to be Trusty](https://travis-ci.org/pypa/warehouse/jobs/413453666#L20) instead of __Xenial__ as we requested in this PR's changes the __.travis.yml__ file.

According to travis-ci/travis-ci#9069, if the Travis worker is less than Xenial then the [download of Python 3.7 will fail](https://travis-ci.org/pypa/warehouse/jobs/413453666#L431)

See #4488 for possible next steps...

### CODE REVIEW

**Comment by ewdurbin** [comment]
Celery needs Python 3.7 support before we can move forward. It appears this will come with Celery version 4.3, which the maintainers indicate should occur by October.

**Comment by pradyunsg** [comment]
This also moves to a full blown VM on their service though. That'll cause a slight slowdown.

**Comment by ewdurbin** [comment]
Kombu released an update... that may help? worth a shot!

**Comment by ewdurbin** [comment]
Kombu is python3.7 compatible as of #5402... let's see how this goes!

**Comment by ewdurbin** [comment]
tested locally, looks like we still need a celery release.

**Pull request closed without merging**
