### PR TITLE
Update development troubleshooting docs

### PR DESCRIPTION
**Pull request by asfaltboy**
This change removes the warning in `LocalFileStorage` under `packaging/services.py`, and updates the documentation as described in ticket #4309.

### CODE REVIEW

**Comment by di** [comment]
This was fixed in https://github.com/pypa/warehouse/pull/4360, sorry @asfaltboy!

**Comment by di** [comment]
Sorry, missed that there were docs changes here too. Could you revise this to leave the warning in place?

**Comment by asfaltboy** [comment]
Sure thing, bit later though, right now I'm stuck boarding my flight

**Comment by asfaltboy** [comment]
I've rebased over latest master, to resolve conflicts, and removed the changes in `packaging/services.py`. I'm about to take off, please let me know if there's anything else to address in this commit.

On an unrelated note, one of the other contributors, using linux, had trouble running `make initdb` while the containers were up. The error was something about postgresql refusing to drop the database while a connection was still open. This we fixed by simply <kbd>ctrl+c</kbd>-ing out of the `make serve` command and running `make initdb` again. Perhaps we should update the docs to reflect this scenario as well?

**Comment by dstufft** [comment]
Thanks! ✨

**Pull request merged**
