### PR TITLE
Route URL in error message(for invalid project name) to Test PyPI

### LINKED ISSUE #3186: Make error message (for invalid project name) work with Test PyPI
Right now, when someone tries to upload a package to PyPI but the project name they want to use is not a project name we allow, the error message we send them includes -- hardcoded -- the URL https://pypi.org. Instead, we should use Pyramid's URL routing to refer to the URL of the PyPI in question, thus ensuring that we send error messages that, as appropriate, refer to pypi.org, test.pypi.org, or any other future PyPI.

To fix this, look at `warehouse/forklift/legacy.py` and `tests/unit/forklift/test_legacy.py` ([the test is `test_fails_with_invalid_names`](https://github.com/pypa/warehouse/blob/master/tests/unit/forklift/test_legacy.py#L872)), and make changes similar to the changes I made in #3183. If you're used to string substitution/string formatting in Python, this should be a relatively approachable first Warehouse issue.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

### PR DESCRIPTION
**Pull request by pgadige**
Fixes #3186

### CODE REVIEW

**Comment by ewdurbin** [comment]
@pgadige thank you for your contribution! I think we should stick with returning an absolute URL though.

@di would one of https://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.static_url work here?

**Comment by ewdurbin** [comment]
never mind! I completely misread :)

**Comment by di** [comment]
@ewdurbin `route_url` produces an absolute URL like `https://pypi.org/help/#project-name`, `static_url` is for static assets.

**Comment by brainwane** [comment]
Thanks, @pgadige! Would you like a suggestion for another small issue to fix?

**Comment by pgadige** [comment]
Thank you, @brainwane I'd love to work on another small issue(preferably Python, CSS, docs)
Thank you, @di for reviewing the code and approving it. 
Thank you, @ewdurbin for `request.static_url` I learnt a new thing today!

**Comment by brainwane** [comment]
@pgadige How about #3139?

**Pull request merged**
