### PR TITLE
Copy pip command to clipboard

### PR DESCRIPTION
**Pull request by karan**
#818 so far...

Does not implement #819.

### CODE REVIEW

**Comment by dstufft** [comment]
Ok, after playing with this, for some reason this seems to work if you import it like:

```javascript

import Clipboard from "clipboard/dist/clipboard";
```

I'm not entirely sure *why*, but it seems to work.

**Comment by dstufft** [comment]
Ok, figured out why, and a better way of handling this... Basically ``clipboard.js``'s ``package.json`` is a bit hinky and it is pointing to an ES6 module even though it should be a CommonJS module. That doesn't fully work *BUT* they also include the babel compiled CommonJS module inside of ``dist/``. So that uses that instead of their ES6 module.

This can be better fixed with this patch to your branch:

```diff
diff --git a/Gulpfile.babel.js b/Gulpfile.babel.js
index b7e283e..8acc441 100644
--- a/Gulpfile.babel.js
+++ b/Gulpfile.babel.js
@@ -56,6 +56,9 @@ let webpackConfig = {
   },
   resolve: {
     modules: [ path.resolve(staticPrefix, "js"), "node_modules" ],
+    alias: {
+      "clipboard": "clipboard/dist/clipboard",
+    },
   },
 };
 
```

This will tell webpack to replace ``"clipboard"`` with ``"clipboard/dist/clipboard"`` whenever used in an import statement.

**Comment by karan** [comment]
Oh wow - that's beyond my knowledge of babel. But thanks for digging that up.

I've updated the PR with the change. (Added an empty file for tooltip)

**Comment by dstufft** [comment]
There is a lint failure here, otherwise this looks pretty good to me.

**Comment by karan** [comment]
ah lints. fixed it!

**Comment by dstufft** [comment]
✨

**Pull request merged**
