### PR TITLE
Accept GitHub-flavored Markdown as a variant for package descriptions

### PR DESCRIPTION
**Pull request by jonparrott**
**Note**: Do not merge until `readme_render` `18.0` is published.

Towards https://github.com/pypa/packaging-problems/issues/126.

### CODE REVIEW

**Comment by brainwane** [comment]
@lgh2 will be reviewing this today.

**Comment by jonparrott** [comment]
`readme_renderer` 18.0 is out, this can now be merged. :)

/cc @dstufft @di

**Comment by dstufft** [comment]
We'll actually need to get 18.0 into Warehouse first too, which we should get a PR from pyup relatively soon.

**Comment by jonparrott** [comment]
that PR is https://github.com/pypa/warehouse/pull/3483

**Comment by jonparrott** [comment]
Thank you @di! Do you have any idea when this will be deployed to testpypi/pypi? I'd like to test it out and such.

**Comment by di** [comment]
@jonparrott Deployments take about 5-10mins, so it's out now.

**Pull request merged**
