### PR TITLE
Add cancel action to ConfirmController

### LINKED ISSUE #3067: Clear input when the user closes the modal
## How to reproduce:

- Log in as a package maintainer
- Go to the 'projects' page and select a project
- Go to a release
- Click on the 'delete release' button
- Enter something into the confirmation input in the modal
- Close the modal (either with 'cancel' or with the cross at the top of the modal)
- Click on 'delete release' button again

## What happens

The second time the user launches the modal, the text from the first time is still in the input

## What should happen

The second time the user launches the modal, the input should be empty

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

### PR DESCRIPTION
**Pull request by mds325**
Fixes #3067 

* Clean input value

### CODE REVIEW

**Comment by di** [comment]
Thanks @mds325!

**Comment by brainwane** [comment]
@mds325 Thanks! if you'd like a suggestion for a next issue to work on, please say so and I'll suggest one. :)

**Comment by mds325** [comment]
@brainwane Of course I'd like a suggestion

**Comment by brainwane** [comment]
Thanks, @mds325! How about #1303?

Also, remind me, will you be joining us at any of the [packaging-related sprints](https://wiki.python.org/psf/PackagingSprints)?

**Pull request merged**
