### PR TITLE
Add API endpoint to list all packages with latest versions

### LINKED ISSUE #347: Add API endpoint to get latest version of all projects
There are projects like https://release-monitoring.org/ which want to monitor PyPI to see when new versions of specific projects are released. Currently this requires doing 1 HTTP request per tracked project which can easily turn into hundreds or thousands of HTTP requests. Offering an endpoint that simply lists the names and versions of all projects can make this take a single HTTP request.

### PR DESCRIPTION
**Pull request by AMDmi3**
Should fix #347. Lacks tests and completely untested yet.

### CODE REVIEW

**Comment by brainwane** [comment]
Thanks for working on this, @AMDmi3!

The folks working on Warehouse have just gotten [funding to concentrate on improving and deploying Warehouse](https://pyfound.blogspot.com/2017/11/the-psf-awarded-moss-grant-pypi.html), and will in December kick off work towards [the first milestone: redirecting pypi.python.org to pypi.org](https://github.com/pypa/warehouse/milestone/1). So if you have time to work further on this soon, the maintainer team should be fairly responsive after the kickoff. Thanks.

**Comment by di** [comment]
Hi @AMDmi3, are you able to bring this PR to a merge-able state? Or should we close it and let someone else work on #347?

**Comment by brainwane** [comment]
I've just pinged @AMDmi3 again via email.

**Comment by di** [comment]
Thanks @brainwane. I'm going to close this, we should probably solve #347 by adding a new endpoint to the JSON API, not the legacy XML-RPC API.

**Comment by AMDmi3** [comment]
I don't think I want to set up warehouse installation to test this code. If nobody from more involved warehouse developers is willing to do this, feel free to drop this.

**Pull request closed without merging**
