### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by minho42**
New pull request after reverting back intentional misspelling 'exmaple' in tests/unit/forklift/test_legacy.py

### CODE REVIEW

**Comment by di** [comment]
Just curious, how did you find all these typos?

**Comment by minho42** [comment]
> Just curious, how did you find all these typos?

Made a simple script to list all words to compare with common misspellings.
But had to go through manually for the most of them.
Trying to improve the script to reduce the manual work.

**Comment by alex** [comment]
FWIW you might be interested in the `topy` package, which has similar typo-finding logic.

**Comment by minho42** [comment]
> FWIW you might be interested in the `topy` package, which has similar typo-finding logic.



> FWIW you might be interested in the `topy` package, which has similar typo-finding logic.

Thanks. I'll give it a try.

**Comment by brainwane** [comment]
@minho42 Thanks! Let us know if you'd like a suggestion for something else to help with in the world of Python packaging!

**Pull request merged**
