### PR TITLE
Fixed alignment for author_profile on tablet and smaller devices

### LINKED ISSUE #6372: Align author_profile on tablet
## Current design
Screenshot from 2019-08-06 07-11-48

## Suggestion
Screenshot from 2019-08-06 07-12-00

---

**Screenshot Required**: This issue will require an update to the visual design of the site. To help our team give you faster feedback, include a screenshot in your Pull Request.

### PR DESCRIPTION
**Pull request by backtrackbaba**
Resolves #6372 

Screenshot for visual confirmation
fixed-author_profile

### CODE REVIEW

**Comment by di** [comment]
Hi @backtrackbaba, are you able to resolve my comment here? https://github.com/pypa/warehouse/issues/6372#issuecomment-724287065

**Comment by backtrackbaba** [comment]
Hey @di, I'm sorry I was not well and away from stuff. I've resolved it and I'll push it in a few hours.

Sorry for the delay

**Comment by di** [comment]
@backtrackbaba No worries! Just wanted to check in, no rush.

**Comment by backtrackbaba** [comment]
Thank you for understanding @di. I've added the commit as discussed in https://github.com/pypa/warehouse/issues/6372#issuecomment-724287065

Here are the screenshots of various sizes

**Large Devices (1000 px and 1001 px)**
large-devices

**Small Devices (400 px and 401 px)**
small-devices

**Comment by di** [comment]
Thanks @backtrackbaba!

**Pull request merged**
