### PR TITLE
7782 user profile eliminate extra email space

### PR DESCRIPTION
**Pull request by JohnHillegass**
For 
#7782

Use HTML and CSS to get rid of the extra space. Seems that this was an issue because p is a block element. The divs allow us to style them exactly as we'd like so offer more flexibility for this.

### CODE REVIEW

**Comment by di** [comment]
Seems good to me, I'll let @nlhkabu review as well. Could you include a screenshot?

**Comment by JohnHillegass** [comment]
Awesome! Thanks @di. Here are the screenshots:

Logged Out
Screen Shot 2020-04-20 at 7 56 45 PM

Logged In
Screen Shot 2020-04-20 at 7 56 15 PM

**Comment by di** [comment]
LGTM!

**Comment by nlhkabu** [comment]
Thank you @JohnHillegass! :tada:

**Pull request merged**
