### PR TITLE
fixes issue #6880

### LINKED ISSUE #6880: Long username overflows on profile page
A sufficiently long username overflows on the user's profile page:

Screen Shot 2019-10-18 at 4 06 31 PM

This will become more of a problem once #5944 is resolved and email addresses appear here as well.

### PR DESCRIPTION
**Pull request by sargamm**
I have changed the overflow property for the required classes in author-profile.scss.

Fixes #6880.

### CODE REVIEW

**Comment by di** [comment]
Screenshot of this change:

Screen Shot 2019-10-21 at 11 06 28 AM

I think we need some additional discussion in #6880.

**Comment by sargamm** [comment]
I have made the required changes. Please have a look

**Comment by di** [comment]
This hides the overflow instead of wrapping it:

Screen Shot 2019-10-29 at 4 45 53 PM

Are you able to run warehouse locally and test these changes before committing them?

**Comment by sargamm** [comment]
I tested locally, it's working for me. Just recheck once @di

**Comment by di** [comment]
Sorry, but it still doesn't work. The name wraps but the username just overflows and the overflow is hidden.

Screen Shot 2020-01-02 at 4 07 37 PM

You'll want to remove the `overflow: hidden;` line you've added (we never want this to happen) and instead add `word-wrap: break-word;` to the `&__meta` block, as this is the "metadata" including the username that is shown in the author profile.

**Comment by sargamm** [comment]
Oh I misunderstood it and did only for the Name,sorry! I have made the required changes now. can you have a look?

**Comment by di** [comment]
This looks correct now:

Screen Shot 2020-01-14 at 2 09 48 PM

**Pull request merged**
