### PR TITLE
Manage projects mobile ui

### PR DESCRIPTION
**Pull request by nlhkabu**
## Collaborators

screenshot from 2018-01-31 08-00-14
screenshot from 2018-01-31 08-00-04
screenshot from 2018-01-31 07-59-57

## Releases

screenshot from 2018-01-31 08-02-56
screenshot from 2018-01-31 08-02-40
screenshot from 2018-01-31 08-02-25

### CODE REVIEW

**Comment by nlhkabu** [comment]
TODO before we can merge this PR

- Make buttons line up
- Make manager 'projects' page better on mobile

**Comment by nlhkabu** [comment]
Manager projects on mobile

screenshot from 2018-01-31 19-57-58

**Comment by nlhkabu** [comment]
Button alignment (Chrome, FF):
screenshot from 2018-01-31 20-05-39
screenshot from 2018-01-31 20-05-27

**Comment by nlhkabu** [comment]
hi @di, this is ready to go on my side.  Please test each of the manage projects pages on mobile (or equivalent resolution) to confirm. Thanks

**Comment by di** [comment]
@nlhkabu The search box is a little confusing in the mobile UI, especially on a page which lists the user's projects:

warehouse local_manage_projects_ nexus 5x

Do you think it makes sense to hide it on mobile when the user is in the logged-in section of the site? I don't think this should be a blocker for this PR but maybe something to consider in the future.

**Comment by nlhkabu** [comment]
:tada: :tada: :tada: :tada: :tada:

**Comment by nlhkabu** [comment]
Thanks @di. I've opened #2868 to address your concern.  I agree that we should remove it here :)  I'll make a separate PR

**Pull request merged**
