### PR TITLE
Improve FAQ

### PR DESCRIPTION
**Pull request by brainwane**
* Start to address #3016 by adding an FAQ item on account recovery.
* Add CoC macros for answers that suggest users file tickets.
* Restructure the "how can I contribute?" answer to include financial donation.
* Fix prose style throughout.

### CODE REVIEW

**Comment by nlhkabu** [comment]
hi @brainwane - I feel like the FAQ is getting pretty long (a good thing!).
Could we maybe add some sub headings in the list at the top to break up the questions into sections?

**Comment by brainwane** [comment]
Absolutely -- happy to. I was thinking something like `<h3>`? Do you want me to use any particular `id` or `class`?

**Comment by nlhkabu** [comment]
The sub titles should be `<h2>`.
We should then change the titles for each question to `<h3>`

If you can make this change, I can then add a commit to update the styles (I'd like to refactor the `.common-question` CSS anyway)?

**Comment by brainwane** [comment]
@nlhkabu Here's an update with subject headings which, of course, looks awful because the CSS hasn't been updated yet. :) Thoughts on the basic structure??

**Comment by nlhkabu** [comment]
Hi @brainwane - I was thinking that the `<h2>` would be at the top, e.g.

```
<h2>Basics</h2>
<ul>
  <li><a href="#packages">{{ packages() }}</a></li>
  <li><a href="#installing">{{ installing() }}</a></li>
  <li><a href="#publishing">{{ publishing() }}</a></li>
  <li><a href="#verified-email">{{ verified_email() }}</a></li>
</ul>

<h2>Integrating</h2>
<ul>
  <li><a href="#APIs">{{ APIs() }}</a></li>
  ...

```

**Comment by brainwane** [comment]
Aha, thanks, got it, @nlhkabu - fixed.

**Comment by brainwane** [comment]
Ready for re-review.

**Comment by nlhkabu** [comment]
hey @brainwane - I was thinking it could be useful to make the `<h2>`s links as well?

**Comment by brainwane** [comment]
@nlhkabu You're right. Fixed and ready for re-review.

**Comment by di** [comment]
Hmm, something went wrong here. There's a lot of space between the top headings:

screen shot 2018-03-14 at 1 43 06 pm

And it looks like we lost the little question mark and the spacing around the questions as well.

Before:
screen shot 2018-03-14 at 1 44 22 pm

After:
screen shot 2018-03-14 at 1 44 11 pm

**Comment by brainwane** [comment]
@di Right, that's actually expected right now. @nlhkabu is going to add some CSS changes to make this look right once I have the headers sorted.

**Comment by brainwane** [comment]
@nlhkabu If you're having trouble pushing to my branch, go ahead and just share the CSS changes with me somehow - a gist, a file emailed to me, something pasted here, a commit to a separate branch of yours, whatever is easiest. And I'll incorporate it so we can get this reviewed and merged.

**Comment by nlhkabu** [comment]
New styles pushed @brainwane:

localhost_help_

One thing I wonder - would "Problems" be better as "Troubleshooting" ?

**Comment by brainwane** [comment]
Thanks for the styling, @nlhkabu!

I actually like "Problems" for being straightforward and less idiomatic than "Troubleshooting" (for less fluent English speakers). If you have a strong preference, I can bow to it, but I have a preference for "Problems".

**Pull request merged**
