### PR TITLE
Fix a s/as/has/ typo in `basic-auth-with-2fa`

### PR DESCRIPTION
**Pull request by webknjaz**
Ref #10836

### CODE REVIEW

**Comment by webknjaz** [comment]
_(noticed this during translation)_

**Review by ewdurbin — APPROVED** [review]

**Comment by di** [comment]
Also needs done to https://github.com/pypa/warehouse/blob/main/warehouse/templates/email/basic-auth-with-2fa/body.txt

**Comment by webknjaz** [comment]
@di done!

**Review by di — APPROVED** [review]
Thanks! And thanks for translating!

**Pull request merged**
