### PR TITLE
docs/getting-started: formatting fixes, add macOS troubleshooting

### PR DESCRIPTION
**Pull request by woodruffw**
`make build` can fail on macOS if `pg_config` isn't installed, which
it isn't by default.

This patch updates the docs to include troubleshooting steps for
installing `pg_config` (via `libpq` via `brew`) on macOS.

It also fixes a couple of formatting nits (incorrect block alignment, a broken link, a mis-spaced comma).

### CODE REVIEW

**Comment by woodruffw** [comment]
See also https://github.com/pypa/warehouse/issues/6782, although the efficient cause of the error there is different.

**Review by ewdurbin — APPROVED** [review]

**Comment by ewdurbin** [comment]
Can you please rebase? I'm unable to update the branch, likely due to a setting on your fork.

**Comment by woodruffw** [comment]
> Can you please rebase? I'm unable to update the branch, likely due to a setting on your fork.

Whoops, I'll see if I can fix that.

**Comment by woodruffw** [comment]
Weird -- normally there's a checkbox allowing the upstream to modify the branch here:

Screen Shot 2022-01-20 at 12 58 13 PM

Might be because this is an old fork...

**Pull request merged**
