### PR TITLE
Check if another file has been uploaded with the same blake2 digest

### LINKED ISSUE #2490: Validate Blake2 Uniqueness prior to saving
For some reason sometimes people are uploading files that already exist with different filenames. I'm not sure if there is a valid use case for this, but if there is we need to either remove the ``UNIQUE`` constraint on the blake2 hash or if there isn't we should validate this before we attempt to save the row.

---

https://sentry.io/python-software-foundation/warehouse-production/issues/147880375/

```
IntegrityError: duplicate key value violates unique constraint "release_files_blake2_256_digest_key"
DETAIL:  Key (blake2_256_digest)=(1d31e5fd783d7ce96471b6d66ba3dd59e3e0722811ecbf5c19173a5194be514c) already exists.

  File "sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)

IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "release_files_blake2_256_digest_key"
DETAIL:  Key (blake2_256_digest)=(1d31e5fd783d7ce96471b6d66ba3dd59e3e0722811ecbf5c19173a5194be514c) already exists.
 [SQL: 'INSERT INTO release_files (name, version, python_version, requires_python, packagetype, comment_text, filename, path, size, has_signature, md5_digest, sha256_digest, blake2_256_digest) VALUES (%(name)s, %(version)s, %(python_version)s, %(requires_python)s, %(packagetype)s, %(comment_text)s, %(filename)s, %(path)s, %(size)s, %(has_signature)s, %(md5_digest)s, %(sha256_digest)s, %(blake2_256_digest)s) RETURNING release_files.id'] [parameters: {'name': 'treelite', 'version': '0.1a1', 'python_version': 'cp27', 'requires_python': None, 'packagetype': 'bdist_wheel', 'comment_text': '', 'filename': 'treelite-0.1a3-cp27-cp27m-macosx_10_6_intel.whl', 'path': '1d/31/e5fd783d7ce96471b6d66ba3dd59e3e0722811ecbf5c19173a5194be514c/treelite-0.1a3-cp27-cp27m-macosx_10_6_intel.whl', 'size': 1574670, 'has_signature': False, 'md5_digest': '32229792ce7968ecd29f9b099cb69644', 'sha256_digest': 'eea762a38b556c0a1f76640be5fcea73eb897d67dc5006dbe590162fbdc5bdea', 'blake2_256_digest': '1d31e5fd783d7ce96471b6d66ba3dd59e3e0722811ecbf5c19173a5194be514c'}]
(44 additional frame(s) were not displayed)
...
  File "warehouse/config.py", line 85, in require_https_tween
    return handler(request)
  File "warehouse/static.py", line 78, in whitenoise_tween
    return handler(request)
  File "warehouse/utils/compression.py", line 93, in compression_tween
    response = handler(request)
  File "warehouse/raven.py", line 41, in raven_tween
    return handler(request)
  File "warehouse/cache/http.py", line 69, in conditional_http_tween
    response = handler(request)

IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "release_files_blake2_256_digest_key"
DETAIL:  Key (blake2_256_digest)=(1d31e5fd783d7ce96471b6d66ba3dd59e3e0722811ecbf5c19173a5194be514c) already exists.
 [SQL: 'INSERT INTO release_files (name, version, python_version, requires_python, packagetype, comment_text, filename, path, size, has_signature, md5_digest, sha256_digest, blake2_256_digest) VALUES (%(name)s, %(version)s, %(python_version)s, %(requires_python)s, %(packagetype)s, %(comment_text)s, %(filename)s, %(path)s, %(size)s, %(has_signature)s, %(md5_digest)s, %(sha256_digest)s, %(blake2_256_digest)s) RETURNING release_files.id'] [parameters: {'name': 'treelite', 'version': '0.1a1', 'python_version': 'cp27', 'requires_python': None, 'packagetype': 'bdist_wheel', 'comment_text': '', 'filename': 'treelite-0.1a3-cp27-cp27m-macosx_10_6_intel.whl', 'path': '1d/31/e5fd783d7ce96471b6d66ba3dd59e3e0722811ecbf5c19173a5194be514c/treelite-0.1a3-cp27-cp27m-macosx_10_6_intel.whl', 'size': 1574670, 'has_signature': False, 'md5_digest': '32229792ce7968ecd29f9b099cb69644', 'sha256_digest': 'eea762a38b556c0a1f76640be5fcea73eb897d67dc5006dbe590162fbdc5bdea', 'blake2_256_digest': '1d31e5fd783d7ce96471b6d66ba3dd59e3e0722811ecbf5c19173a5194be514c'}]
```

### PR DESCRIPTION
**Pull request by alanbato**
This tries to resolve  #2490

I'm not sure if the uniqueness of the blake2 digest should be validated on file uploading or before, or if hijacking on the same "File already exists" message is helpful enough.

Also, I'm getting a weird error on my test, making it fail. Something about the request object missing a 'user' attribute.

Thanks for your feedback y'all.
🐍

### CODE REVIEW

**Comment by di** [comment]
The error is because your test is getting to this line:

```python
            request.db.add(
                JournalEntry(
                    name=release.project.name,
                    version=release.version,
                    action="add {python_version} file {filename}".format(
                        python_version=file_.python_version,
                        filename=file_.filename,
                    ),
>                   submitted_by=request.user,
                    submitted_from=request.remote_addr,
                ),
            )
```

Which means it's trying to add the file being uploaded, so it seems like either something is wrong with your test, or with the new logic you added.

**Comment by di** [comment]
Hey @alanbato, need any help or more direction here?

**Comment by brainwane** [comment]
I think @alanbato [is having computer problems](https://twitter.com/alanbato/status/972266164855410688).

**Comment by alanbato** [comment]
Yes I am 😢
If anyone wants to continue and build on this PR, please do so. I'll ping this thread when my computer gets better 😓

**Comment by brainwane** [comment]
Thanks for all your work on this @alanbato which @yeraydiazdiaz was able to build on. Hope your computer heals soon!

**Comment by alanbato** [comment]
@brainwane I'm glad it was of help :) And my computer lives to see another, so I'm ready to start contributing again! :sunglasses:

**Comment by brainwane** [comment]
@alanbato I'd love your help with #3151.

**Pull request closed without merging**
