### PR TITLE
Test if tabs exist before running JavaScript

### PR DESCRIPTION
**Pull request by alexmuller**
This JavaScript executes on every page so if there's no mobile button element on the page the call to `getComputedStyle` will cause an error. This change catches that case.

### CODE REVIEW

**Comment by alex** [comment]
Code looks reasonable to me, does it make more sense to simply not run this function on pages it's not relevant on?

**Comment by alexmuller** [comment]
Yep that's possible, I think the best approach would be:

- Add a new `block` just before the `</body>`
- Change this file to return a function
- On the packaging detail page, add a bit of JavaScript to the end of the body block to run the function

As far as I can tell it's just the packaging detail page which has these tabs. I'll have a go at what that solution could look like.

**Comment by di** [comment]
Seems like this is still happening somehow.

**Comment by di** [comment]
Urgh this is a PR not an issue...

**Pull request closed without merging**
