### PR TITLE
Link to API token form from manage project page

### PR DESCRIPTION
**Pull request by nlhkabu**
Partially addresses #6551 

## With verified email
Screenshot from 2019-09-05 06-52-30

## Without verified email
Screenshot from 2019-09-05 06-54-11

### CODE REVIEW

**Comment by nlhkabu** [comment]
@woodruffw - is there a way that we can set up this URL so that when we land on the 'create token' page, the project is pre-selected in the form?  E.g. for this project ("clandestined") landing on the page, it would look like this:

Screenshot from 2019-09-05 07-00-06

**Comment by woodruffw** [comment]
> is there a way that we can set up this URL so that when we land on the 'create token' page, the project is pre-selected in the form? E.g. for this project ("clandestined") landing on the page, it would look like this:

Hmm, I'm not sure that there is with the current form setup -- we handle defaulting to the user's previously selected scope on form error by checking `create_macaroon_form.token_scope.data`, but I don't believe there's a direct way to set that from `route_path`.

A more invasive option would be to add some kind of route parameter like `default_scope` that we could prioritize over the state of `create_macaroon_form`, but that adds complexity. Maybe @dstufft or @ewdurbin have opinions/insight here?

**Comment by nlhkabu** [comment]
@woodruffw do you think we should merge this PR and open a separate ticket for pre-selecting the form?

**Comment by woodruffw** [comment]
> do you think we should merge this PR and open a separate ticket for pre-selecting the form?

Yeah, I think that's a good solution for now.

**Pull request merged**
