### PR TITLE
Sorting projects on user pages by creation date

### PR DESCRIPTION
**Pull request by mahmoud**
Per #2206, this one-line change sorts projects on a user's page by time of last release. Works in the compose locally, all tests passing, as expected.

Couple of notes on implementation: I took the approach of doing a simple `.sort()` on the distributions because we're already fetching all the records anyways, and postgres's `ORDER BY` requires the first field to equal that of the `DISTINCT` clause when it's present ([docs](https://www.postgresql.org/docs/9.1/static/sql-select.html#SQL-DISTINCT)). I don't think it'll be a big deal, and I'd rather not complicate the query, just to do the sort on the db.

Hope this works for you!

### CODE REVIEW

**Comment by dstufft** [comment]
You're missing coverage-- I'm guessing because the lambda isn't getting called.

**Comment by dstufft** [comment]
But to be explicit, this looks fine to me and the rationale for doing it in memory instead of in the DB seems solid.

**Comment by mahmoud** [comment]
Ah, so the test that covered the query returned 0 results, I guess. I'll see if I can track that down.

**Comment by brainwane** [comment]
Thanks for your pull request, @mahmoud!

The folks working on Warehouse have just gotten [funding to concentrate on improving and deploying Warehouse](https://pyfound.blogspot.com/2017/11/the-psf-awarded-moss-grant-pypi.html), and will in December kick off work towards [the first milestone: redirecting pypi.python.org to pypi.org](https://github.com/pypa/warehouse/milestone/1). So if you have time to revise this PR, then after that kickoff we'll be pretty responsive with feedback.

**Comment by mahmoud** [comment]
Hey @brainwane! How fun, running into you here :)

So this would-be-1-line PR died for me because I couldn't run tests locally, even when the site ran. Unfortunately, the coverage requirement is very high, but the parity between tests and site behavior is low. Specifically, the fake users created for the tests don't have any projects, so my one line was only half-hit. In any case, I followed the instructions in the guide, I got all manner of errors and I just ended up going down the rabbit hole of the Makefile.

I'd like to see some of those resources go toward making that workflow better, because if it's this hard to make a small change to Warehouse, it's pretty hard to tell myself and others that it's a good way to spend their time. 

Anyways, I'll keep an eye on this and am happy to give it another go once things improve.

**Comment by brainwane** [comment]
Hi @mahmoud and thanks for the feedback! I'm happy to run into you here as well, and I'm sorry you had this trouble. :(

So it sounds like one problem you ran into is that -- even on `master` -- you couldn't get the tests to run (is that right?) and another problem you ran into is that the fake (test) users didn't have any projects. I see (via `git log -- tests/unit/`) that in the last two months we've added a lot more to our test coverage and the available test classes, and I think we've addressed that issue; thanks for bringing it up.

So if you wouldn't mind trying to get the tests to run on `master` and letting us know -- in IRC in #pypa-dev on Freenode, or in a new issue -- if you still have trouble running them, that would be great! We have, just in the last couple months, smoothed out some of the new contributor snags, and we'd be glad to find and smooth out any more.

Thanks.

**Comment by brainwane** [comment]
@mahmoud I won't bother you about this today, but new contributors generally have an easy time of it now, getting the tests to run, so I hope you'll come back and try again if you have other future improvements to make. :)

**Pull request closed without merging**
