### PR TITLE
Manage emails

### LINKED ISSUE #2830: Manage Account: Change emails
From #423: From the 'manage account' page, a logged-in user should be able to do the following:

* view all emails associated with their account
  * including the verified/unverified and/or primary status of each email address
* add a new email address
  * should send a verification email to that address.
* change primary email address

### PR DESCRIPTION
**Pull request by di**
Fixes #2830. This PR adds the ability to add and remove emails, as well as change the primary email address. It also adds the ability to verify email addresses (and re-send verification emails).

screen shot 2018-02-06 at 6 16 42 pm

@nlhkabu I was imaginging that the "Primary", "Verified" and "Unverified" `span`s could be colored labels. Also imagining that the "Add" and "Save" buttons would be inline with their respective input fields.

### CODE REVIEW

**Comment by brainwane** [comment]
@lgh2, Dustin and I would like for you to review this PR. Please:

* grab Dustin's branch onto your local machine
* run the tests locally (a measure to ensure that you can do so and that there's no logistical trouble),
* test and try to break functionality, especially edge cases
* look at the code changes and say if there's a chunk of code that you have questions about

Edge cases Dustin would like you to investigate start with:
* add an email, then delete it, then follow the verification link — what happens?
* add an email, log out, then follow the verification link — what happens?
* add an email for user A, log in as user B, follow the verification link — what happens?
* open the management page in two separate tabs, and try to delete the same email twice — what happens?

If you think of more edge cases to test, please go ahead and try them!

**Comment by lgh2** [comment]
Thank you! I will test it.

**Comment by lgh2** [comment]
Here are screenshots associated with my previous comment: 

*add an email, log out, then follow the verification link — what happens?* 

This screenshot shows the verified email address shown in the banner when the user is logged out, after following the link in the verification email: 

not_logged_in_email_displayed

*add an email for user A, log in as user B, follow the verification link — what happens?* 

This screenshot shows an email associated with another user's account displayed when I am logged in, after I clicked the email verification link while logged in: 

other_login_email_verified

**Comment by di** [comment]
@lgh2 Thanks very much for the QA! And great find. I've pushed a commit which requires that a user must be logged in before they can verify a new email address. Can you re-test the second and third use cases?

**Comment by lgh2** [comment]
Thank you! 
Once again, I'm using Chrome Version 64.0.3282.119 (Official Build) beta (64-bit) on Linux Mint 18.1 (Ubuntu Xenial 16.04)

Here are the second and third use cases: 

_add an email, log out, then follow the verification link — what happens?_

* email banner is no longer displayed, I am redirected to the login page. 
no-banner-after-logout

* when I log in again, the email is verified. 

_add an email for user A, log in as user B, follow the verification link — what happens?_

* When I try following the link from user A while logged in as user B, I get an "email not found" error, displayed in a banner: 

email-not-found

* When I log in to user A, the email is still unverified.

**Comment by di** [comment]
Great, thanks @lgh2!

**Comment by brainwane** [comment]
If anyone feels like testing this, a few more edge cases you could check:

* do the views give the user the appropriate error if you try to leave the "Add email address" field empty and click the Add button?
* what does the application do if you try to put multiple email addresses in the "Add email address" field, separated with a comma?
* does the email that we send look ok both in HTML and in plain text?
* do we give the user good error messages for invalid email addresses? (addresses that, for instance, include spaces or don't have TLDs (example: `sumanah@python`))
* does the Tab key work as you'd expect to tab through these fields/buttons?
* what happens if you try to make up a fake verification link with random characters in it and go to that URL, while logged out and while logged in?
* what does the application do if you try to put something like `"Sumana" <sh@example.com>` or `Sumana <sh@example.com>` in the "Add email address" field, separated with a comma? (When people copy and paste email addresses from email programs sometimes that's the format they end up pasting in.)
* do we deal ok with weird but technically standards-compliant email addresses? (very long, very short, including special characters of various kinds)

**Comment by nlhkabu** [comment]
Looks like my indentation is off - will fix. 

@di can you please review https://github.com/pypa/warehouse/pull/2898/commits/ff75be84e60ed7835bc89a747f9a77a14964018e to make sure I've not lost anything? Thx

**Comment by waseem18** [comment]
@brainwane I've tested the application with the said test cases and everything seems to work perfectly.

I've tested them on both Chrome as well as Firefox browsers.

**Pull request merged**
