### PR TITLE
Add label and title to trove classifier request link

### PR DESCRIPTION
**Pull request by nlhkabu**
screenshot from 2018-04-01 09-42-08

Adds title and label :)

### CODE REVIEW

**Comment by pradyunsg** [comment]
@nlhkabu The link doesn't add a label if you don't have commit access (just tested that with #3489). That bit of the URL could be dropped. :)

**Comment by nlhkabu** [comment]
hmmm... I thought that it would work if I made the PR :(

**Comment by nlhkabu** [comment]
updated @pradyunsg

**Comment by nlhkabu** [comment]
@pradyunsg I've added you as a reviewer - could you please make a formal review?  Thanks

**Pull request merged**
