### PR TITLE
Add warning about docker version for linux users

### PR DESCRIPTION
**Pull request by nanuxbe**
This simple warning would have saved me a lot of time, I think it's worth adding.

### CODE REVIEW

**Comment by di** [comment]
Hmm, https://github.com/pypa/warehouse/pull/4368 just added a recommendation to install from a snap, perhaps this is bad advice? I'm not really familiar with the best way to get Docker on Linux.

**Comment by nlhkabu** [comment]
@dstufft or @ewdurbin could you please advise on this PR? Thx :)

**Comment by ewdurbin** [comment]
I don’t have enough experience using Docker on Linux Desktop/Workstation to assess.

**Comment by di** [comment]
Closing due to lack of response here. If more users experience this we can revisit.

**Pull request closed without merging**
