### PR TITLE
Add a shortlink for projects

### LINKED ISSUE #3143: Add a "shortlink" for projects
**From user testing:**

When viewing projects on PyPI, some users type the URL directly if they know the project name.

We should create a shortlink like`pypi.org/p/myproject` which would redirect to `pypi.org/projects/myproject`

cc @di for feedback / guidance.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

### PR DESCRIPTION
**Pull request by dirn**
To make it easier for people who want to type project URLs, this will
redirect all requests for `/p/<project>/` to `/project/<project>/`.

Closes #3143

### CODE REVIEW

**Comment by di** [comment]
Thanks @dirn!

**Comment by nlhkabu** [comment]
:tada: :tada: :tada:

**Comment by brainwane** [comment]
@dirn if you'd like a suggestion for a next issue to work on, please say so and I'll suggest one. :)

**Comment by dirn** [comment]
I’d be happy to take a look at some issues. Feel free to use the email in my profile if you find that an easier format.

**Comment by brainwane** [comment]
Thanks, @dirn! I may use your email at some future point -- right now I find it useful to make these suggestions in the open, for transparency and cross-linking.

If you'd prefer to start with something small, #3184 would be good.

If you're interested in something larger, take a look at #1190.

And please let us know if you plan to come to any of the [packaging sprints](https://wiki.python.org/psf/PackagingSprints) in the next few months, to work with us in person.

**Pull request merged**
