### PR TITLE
Add default search message, suggestions

### LINKED ISSUE #803: Default search message
We need to add a message for when a search doesn't match any packages.

### PR DESCRIPTION
**Pull request by di**
This fixes #803 by adding a default search message. It also adds a suggestion for the search term when necessary (per the discussion in #803).

@nlhkabu This is definitely missing localization stuff, I wasn't sure how that worked, please advise :)

### CODE REVIEW

**Comment by sigmavirus24** [comment]
@di you have three commits with the same message. It might be worth squashing those (or editing the commit messages to not be identical)

**Comment by di** [comment]
@sigmavirus24 I think you just caught me while rebasing, there is only one commit.

**Comment by sigmavirus24** [comment]
@di that's why I removed my comment ;)

**Comment by nlhkabu** [comment]
thanks for this @di - as I said on the issue - it's awesome. @dstufft set up the translations, so he is in a better position to advise on this than me.

FYI @dstufft I am happy for this to be merged on the design side ;D

**Comment by di** [comment]
@dstufft I found the documentation on translations and took a shot at it.

@nlhkabu FYI, I noticed that long package names cause some wrapping of the "Order Packages By" elements:

screen shot 2016-02-08 at 10 02 19 am

**Pull request merged**
