### PR TITLE
Clean docker images right after build

### PR DESCRIPTION
**Pull request by trishankatdatadog**
One-liner to remove intermediate images right after build, saves around half a Gig on my machine

### CODE REVIEW

**Comment by trishankatdatadog** [comment]
Doesn't seem to be enough:

```
docker-compose build --force-rm static
Building static
Step 1/5 : FROM node:8.15.1 as static
 ---> 8c51cec97ebf
Step 2/5 : WORKDIR /opt/warehouse/src/
 ---> Using cache
 ---> f839441cb486
Step 3/5 : RUN set -x     && apt-get update     && apt-get install --no-install-recommends -y         libjpeg-dev nasm
 ---> Using cache
 ---> b757eb700462
Step 4/5 : COPY package.json package-lock.json .babelrc /opt/warehouse/src/
 ---> Using cache
 ---> 2ad353b7d0d5
Step 5/5 : RUN set -x     && npm install -g npm@latest     && npm install -g gulp-cli     && npm install
 ---> Using cache
 ---> 17463fabe5e0
Successfully built 17463fabe5e0
Successfully tagged warehouse_static:latest
# Mark this state so that the other target will known it's recently been
# rebuilt.
mkdir -p .state
touch .state/docker-build
$ docker images
REPOSITORY          TAG                  IMAGE ID            CREATED             SIZE
warehouse_web       latest               bf1e1a57fdcf        16 seconds ago      433MB
warehouse_worker    latest               bf1e1a57fdcf        16 seconds ago      433MB
<none>              <none>               c11ece5ad24a        48 seconds ago      663MB
<none>              <none>               0c89c1e7236f        2 minutes ago       1.11GB
warehouse_static    latest               17463fabe5e0        3 minutes ago       1.09GB
python              3.7.3-slim-stretch   ca7f9e245002        4 weeks ago         143MB
node                8.15.1               8c51cec97ebf        2 months ago        895MB
$ docker system prune -f
Deleted Images:
deleted: sha256:0c89c1e7236f6fad7684b5719da40943d0f13cd341fa06c9f59ce5263a3f0150
deleted: sha256:689d473324a61bd2e2a1fcf76b49d3f96ccf4f250da2bc89fe561fd997540c68
deleted: sha256:f011f36c0f7888b6d9f62a0e2eda9a5a8a3ccb1fa54d2593e56167416d866bb5
deleted: sha256:0e36c678c78bc5023a83530c0df82de5ca3f7a66391f384adfa27e0cc3989bd0
deleted: sha256:08b95c98358530daadad0c8798d539ddb7c200f06acdcdb8f184fd054f44baa0
deleted: sha256:5dc436348227bf8208db29ede956de785ccf5d089094c6d03400eb45f371ac48
deleted: sha256:d78439f7fa7252e3d677b88123e967b8e6e3ff3834739961d637c893a4c2de2b
deleted: sha256:1191548c84e8e3fd961b783668cdb7a4fff38ecf8ec28f259874affdbab40384
deleted: sha256:c11ece5ad24a1849a80f9f6216d15bf26a3c3cd21b5418d5533249f1792efc08
deleted: sha256:bead0fd1a8456de997ef9d0a0db05cf8fbc3ea287540ffba53cba581efaebbda
deleted: sha256:463a3f22716d07991a5e5d048de0725f4fba1ef25c1d04f413a49346985824c4
deleted: sha256:c16635f8e08a4778fa666e7ec57764ddf0b4b000ac65d53d25cda80ed4da9021
deleted: sha256:cdb70ea175f3e1474f35e11d11f09a71d81a04ac794bbde90ac3ddd4b2b440f4
deleted: sha256:e8b1a21ffeeb361141dad02999831fe3aabda8fce3296891b9c6f6c370f3233e
deleted: sha256:57e4b1a0791dd36fa62ef96332ab709d6c3c6bb337387098e285c5efb51cf9f6
deleted: sha256:25cea53929ae865b95e07494d75ebe661368f3fadaf61f10f5c19175e2b03fa8
deleted: sha256:614e3ab856a10d158e94864ed6d9dae09ea9939bf1c404d6c88e8b4fdaa67e8b
deleted: sha256:891e24fd5ba98dce9e171eba06eb9ba6dc9943a92a2e052b4f585617e1152297
deleted: sha256:e295817470ec9b320c9394566c3a532f821b45d8d57bb62a9023bc1a727a3366
deleted: sha256:81992c9d2a5690534cb1679ba7334f72157ba1aa9f0f4b3544e680755fec8ef5
deleted: sha256:f745008f719948792ffffae2a35996c8334957339257354a4b1a65308a9a8492
deleted: sha256:b7f29006814edb267b0bfdbf8e68d30c5259718a23d6c0da989ebfa850f340eb
deleted: sha256:ef901d78dbba9b5420cbff47f978e37f07136bd013d30bc415b03cf0ae4542b1
deleted: sha256:aa8e9525a2e6c4019272030bb93b4e773f74e7e4004cb3d157cbdf8502c6e1b8
deleted: sha256:a536572feb9710c9c2c2912b58db8c8f57fd5ff701b48e059966698885f0b860

Total reclaimed space: 539.5MB
$ docker images
REPOSITORY          TAG                  IMAGE ID            CREATED             SIZE
warehouse_web       latest               bf1e1a57fdcf        24 seconds ago      433MB
warehouse_worker    latest               bf1e1a57fdcf        24 seconds ago      433MB
warehouse_static    latest               17463fabe5e0        3 minutes ago       1.09GB
python              3.7.3-slim-stretch   ca7f9e245002        4 weeks ago         143MB
node                8.15.1               8c51cec97ebf        2 months ago        895MB
```

**Comment by brainwane** [comment]
@trishankatdatadog is this ready for re-review?

**Comment by trishankatdatadog** [comment]
@brainwane I'd say so

**Comment by ewdurbin** [comment]
remaining concerned about pruning the whole docker environment, I checked and `docker system prune` can accept a `--filter`.

let's add `--filter "label=com.docker.compose.project=warehouse"` to the prune command and this is ready to ship

**Comment by trishankatdatadog** [comment]
@ewdurbin done!

**Comment by ewdurbin** [comment]
Thank you @trishankatdatadog!

**Pull request merged**
