### PR TITLE
Error if no xz installed

### PR DESCRIPTION
**Pull request by trishankatdatadog**
Try to fix #5872

### CODE REVIEW

**Comment by ewdurbin** [comment]
This still doesn't seem to work on latest MacOS... xz installed via Homebrew.

```shell
ewd3imac:warehouse ewdurbin$ git diff
diff --git a/Makefile b/Makefile
index 480a9b72..dc1cdbd4 100644
--- a/Makefile
+++ b/Makefile
@@ -149,6 +149,7 @@ ifneq ($(PR), false)
 endif
 
 initdb:
+       xz -V &> /dev/null || $(error "No xz available on PATH, install xz!")
        docker-compose run --rm web psql -h db -d postgres -U postgres -c "DROP DATABASE IF EXISTS warehouse"
        docker-compose run --rm web psql -h db -d postgres -U postgres -c "CREATE DATABASE warehouse ENCODING 'UTF8'"
        xz -d -f -k dev/$(DB).sql.xz --stdout | docker-compose run --rm web psql -h db -d warehouse -U postgres -v ON_ERROR_STOP=1 -1 -f -
ewd3imac:warehouse ewdurbin$ make initdb
Makefile:152: *** "No xz available on PATH, install xz!".  Stop.
ewd3imac:warehouse ewdurbin$ xz -V
xz (XZ Utils) 5.2.4
liblzma 5.2.4
ewd3imac:warehouse ewdurbin$ which xz
/usr/local/bin/xz
ewd3imac:warehouse ewdurbin$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14.5 (18F132)
      Kernel Version: Darwin 18.6.0
      Boot Volume: ewd3mojave
      Boot Mode: Normal
      Computer Name: ewd3imac
      User Name: Ernest W Durbin III (ewdurbin)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 13 days 53 minutes
```

**Comment by trishankatdatadog** [comment]
WFM... does anyone else want to try?

**Comment by brainwane** [comment]
@di could you give this a try?

**Comment by sayanarijit** [comment]
FYI a `note` section in https://warehouse.readthedocs.io/development/getting-started/ needs update too.

**Pull request closed without merging**
