### PR TITLE
Move show password checkbox

### PR DESCRIPTION
**Pull request by nlhkabu**
screenshot from 2017-12-21 08-14-28
screenshot from 2017-12-21 08-14-16

### CODE REVIEW

**Comment by nlhkabu** [comment]
@di I also noticed that on the register page, only the first password is being revealed.  Can we refactor the JS so that the checkbox shows both the password *and* the password confirmation?

I started doing this, but I got myself into a JS mess :/

**Comment by di** [comment]
Hey @nlhkabu, can you check the "Allow edits from maintainers" box on this PR so I can push a commit to your branch?

**Comment by nlhkabu** [comment]
Hi @di - looks like it's already checked :)

**Comment by di** [comment]
Oops, that was my mistake. I pushed a commit which makes the checkbox toggle both input fields.

**Pull request merged**
