### PR TITLE
detail.html Group most frequently needed info at the top

### PR DESCRIPTION
**Pull request by techtonik**

### CODE REVIEW

**Comment by nlhkabu** [comment]
Sorry, commented in the wrong place:



What thought process are you using here to say that this order is the "most needed"? Do you have any data to back up this specific ordering?

For this change to be complete, you will also need to look at:

    the corresponding div order and mobile titles
    the h2 titles at the top of the downloads and statistics sections

I will also need to see some screenshots to validate this visually.

Thanks :D

**Comment by nlhkabu** [comment]
FYI, this section of code has just been updated to allow direct linking to sub pages (https://github.com/pypa/warehouse/pull/972).  You will probably want to pull down the latest version before making a new PR.

**Comment by techtonik** [comment]
> What thought process are you using here to say that this order is the "most needed"?

Well, usually I "Download" things, then I am interested to see if a package is popular with "Stats", then I need "Version History" if I am revisiting the page for update, and the thing that I need rarely are "Dependencies".

> Do you have any data to back up this specific ordering?

No, not usability testing from here and I doubt that it will be better than some behavior tracker like Google Analytics. Although some people may be unhappy to be tracked.

> You will probably want to pull down the latest version before making a new PR.

It is unlikely that I'll get that deep into a rabbit hole anytime soon. Apache 2.0 licensed code is hard to reuse, so there is little incentive from my side to learn it well.

**Comment by dstufft** [comment]
> It is unlikely that I'll get that deep into a rabbit hole anytime soon. Apache 2.0 licensed code is hard to reuse, so there is little incentive from my side to learn it well.

So you have no intention of actually doing the entire contribution process other than throwing a random patch and then want the folks who are *actually* doing it to do it a particular way?

I'm going to go ahead and close this pull request. Empirical data from PyPI suggests that the thing most people do the *least* is download the files using their browser. I'm not saying that the rest of the ordering here is the best ever or anything like that, but given that we don't have any other data right now and since you've stated you're unlikely to actually continue this PR I see little reason to keep it open.

**Comment by techtonik** [comment]
> So you have no intention of actually doing the entire contribution process other than throwing a random patch and then want the folks who are actually doing it to do it a particular way?

I hope that this work is sponsored by PSF and your company as well by allowing you to work on this, so I guess there is no conflict there. I can just paste screenshots if you like instead of throwing patches. The patches here are to show the concept. I don't want you to do the things that **I want** - I want you to consider things that **some people** may find useful.

I told you why I unlikely to work on this request. If that project carried a different license, I might be able to find funding to work on it too.

**Comment by techtonik** [comment]
And I am a bad coder, so it takes a lot of time for me to learn things like you do in web.

**Pull request closed without merging**
