### PR TITLE
update sphinx to latest version 3.1.2

### PR DESCRIPTION
**Pull request by shireenrao**
Updating Sphinx to the latest version 3.1.2 based on discussions at https://github.com/pypa/pip/issues/8650#issuecomment-665858951`

### CODE REVIEW

**Comment by shireenrao** [comment]
Forcing to restart CI

**Comment by di** [comment]
Hmm, we might want to try and figure out why this wasn't getting updated automatically by Dependabot, could you create an issue?

**Comment by shireenrao** [comment]
Sure, what type of issue should this be filed under?

**Comment by di** [comment]
Just a regular issue is fine: https://github.com/pypa/warehouse/issues/new

**Pull request merged**
