### PR TITLE
[#162] Style error pages.

### PR DESCRIPTION
**Pull request by wlonk**
See #162. A first stab at styling 404 and 500 pages.

### CODE REVIEW

**Comment by wlonk** [comment]
There's obviously wording and style work to do here, but I thought I'd get this up for feedback and review sooner than later. Most of the work was in wiring the pages up; I'm not very familiar with Pyramid, so if there's a better way, please let me know.

**Comment by wlonk** [comment]
Unsure why coverage is reporting failed when it's apparently at 100%. Will deal with it in the morning.

**Comment by willingc** [comment]
@wlonk It looks like the Travis buld is failing a PEP8 check (Click on the Details link above next to `continuous-integration/travis-ci/pr):
screenshot 2015-08-10 19 46 39
It looks like you have imported something that you are not using. 

I am guessing that codecov/project fails for coverage since Travis is not happy. Perhaps double check your config.py file.

**Comment by wlonk** [comment]
Thanks, @willingc! I hadn't realized coverage would complain if there were other test errors.

I had also failed to build the necessary translations files, so I fixed that, and we're green.

But I'm not at all sure that the design here is worth merging yet, so if anyone has any feedback on that, I'd appreciate it too!

**Comment by dstufft** [comment]
Yea, coverage does that because if all the test jobs don't complete it might not have correct data.

**Comment by wlonk** [comment]
Yeah, makes sense.

**Comment by dstufft** [comment]
Going to close this since we've landed #751 which has started with a whole new design of everything. Thanks for the PR!

**Comment by wlonk** [comment]
:+1:

**Pull request closed without merging**
