### PR TITLE
Don't install g++ from a PPA in travis

### PR DESCRIPTION
**Pull request by alex**
I have no idea if this will work

### CODE REVIEW

**Comment by alex** [comment]
The default C++ compiler appears just fine.

This speeds up the tests by a bit.

**Comment by ewdurbin** [comment]
🙏 bless you!

**Comment by ewdurbin** [comment]
for record keeping: these were added in https://github.com/pypa/warehouse/pull/1137 and appear to have been in support of some node dependencies for static builds. it looks like brotli may not have worked with older compilers... but we're good now :)

**Comment by ewdurbin** [comment]
particularly as we don't actually use any assets from travis for deployment, I'm gonna say 🚀

**Pull request merged**
