### PR TITLE
Remove @token usename, pypi: token prefix

### LINKED ISSUE #6345: API tokens: Remove @token and pypi: cases
At some point in the future (perhaps at the end of the API token beta?), support for `@token` as a token username and `pypi:` as a token prefix should end in favor of `__token__` and `pypi-`, respectively.

See #6287, #6342.

cc @brainwane @di @ewdurbin @dstufft

### PR DESCRIPTION
**Pull request by woodruffw**
See #6342.

Closes #6345.

cc @ewdurbin @di @dstufft @brainwane

### CODE REVIEW

**Comment by ewdurbin** [comment]
@brainwane, @di, @dstufft do we have a preference for when this lands? we should notify the list of users shared previously (in private) with some reasonable lead time before merging.

**Comment by di** [comment]
Probably should notify ASAP. We should merge this by the end of the beta period at the latest, but I think @brainwane wanted to roll it out faster, maybe in ~1 week?

**Comment by brainwane** [comment]
Yes. I want to roll it out within the next 3-5 business days so that we can continue the beta, and see if the change causes any NEW problems for beta testers. So we should notify people today, IMO.

**Comment by ewdurbin** [comment]
Notification will go out now, stating 2019-08-09T12:00:00Z (August 9, 2019 12:00:00 UTC) as merge date for this PR.

**Comment by ewdurbin** [comment]
One thought would be to add a custom error message if we see the old `@token` username or `pypi:` prefix, bringing them to this PR?

**Comment by hugovk** [comment]
> Notification will go out now, stating 2019-08-09T12:00:00Z (August 9, 2019 12:00:00 UTC) as merge date for this PR.

When is the merge date? The email that went out says September not August:

> To avoid any interruptions, you must make these changes before 2019-09-09 12:00:00 UTC when https://github.com/pypa/warehouse/pull/6368 is merged.

**Comment by ewdurbin** [comment]
@hugovk that was a typo on my part, merging 2019-08-09 12:00:00 UTC. I'll send a follow up email.

**Comment by brainwane** [comment]
@nlhkabu heads-up per https://wiki.python.org/psf/PackagingWG/2019-08-02-Warehouse - just FYI

**Comment by nlhkabu** [comment]
@ewdurbin before merging, can we please update the text on the `/help` page?

**Comment by ewdurbin** [comment]
@nlhkabu which help text? https://pypi.org/help/#apitoken was already updated in #6342

**Pull request merged**
