### PR TITLE
Reduce package card height

### LINKED ISSUE #1337: Reduce package card height
Now that we have removed uploader information from the card, I think the version looks a bit daft on its own line:

screenshot from 2016-07-02 10-39-36

Suggested fix: move version to next to the package name.

Given that this will make the cards shorter, we can also afford to reduce the margin on each card, which will compress the interface somewhat.

### PR DESCRIPTION
**Pull request by k-nut**
This fixes #1337 by moving the version number of the package to the same line as the name. It also reduces the margins as proposed.
I think this change should also be applied to the markup in `warehouse/templates/packaging/detail.html` but I could not find out where that is displayed. Can someone provide me with a link so that I can test locally and if applicable push another change?

screen shot 2016-10-17 at 12 12 52

### CODE REVIEW

**Comment by di** [comment]
Hey @k-nut, thanks for taking care of this!

The `project_snippet` macro in `warehouse/templates/packaging/detail.html` was originally used in the "Dependencies" tab, [which is currently commented out](https://github.com/pypa/warehouse/blob/master/warehouse/templates/packaging/detail.html#L203-L229). I think it's fine if you update that markup as well, but you won't see anything change.

This LGTM with or without that change, but @nlhkabu should review as well.

**Comment by k-nut** [comment]
Cool, thank you for the quick feedback! I pushed another change that changes the markup in `detail.html` as well.

**Comment by k-nut** [comment]
May I ask what the status of this is? Is there anything that I can do to help move this forwards?

**Comment by dstufft** [comment]
Thanks! Sorry for the delay. I'm going to go ahead and merge this for now. I'll tag it so that @nlhkabu can review it later to ensure she didn't want any changes done to it.

**Pull request merged**
