### PR TITLE
Don't show 'view project' link when there are no releases

### LINKED ISSUE #3069: Do not show 'view project' button when there are no releases
## Steps to reproduce

- Login as a package maintainer
- Go to the projects page
- Click on a project
- Delete all releases on the project

## What happens

The project card at the top of the page shows a 'view project' button:

screenshot from 2018-02-27 08-25-55

## What should happen

The 'view project' button at the top of the page should not show if there is no release.

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

### PR DESCRIPTION
**Pull request by berkerpeksag**
Fixes #3069

### CODE REVIEW

**Comment by brainwane** [comment]
Her @berkerpeksag -- thanks for the PR, and thanks as always for your [past work on Warehouse](https://github.com/pypa/warehouse/commits?author=berkerpeksag) as well!

I don't know whether you saw this, but #3069 has a ["good first issue" tag](https://github.com/pypa/warehouse/labels/good%20first%20issue) (as does #3070 which you fixed in #3074). We've been running low on those as -- happily -- Warehouse has been getting interest and contributions from newcomers, who have been snapping them up. (And, during the MOSS-funded grant period, Dustin, Nicole, and Ernest have the bandwidth to be responsive to them and help them learn.) Since you have a bunch of experience with Warehouse, could I ask you (if you have time to work on Warehouse in the next few months) to steer your way towards some harder issues, the ones the newcomers don't yet have the skills to attempt?

And if you have any suggestions for other relatively easy-to-fix problems in Warehouse, please do file issues -- we can use them!

I'm sorry if this seems discouraging or ungrateful; it isn't meant to be. Thanks for your continuing work on this and the rest of the Python ecosystem.

**Comment by berkerpeksag** [comment]
I didn't specifically pick them from the issues list. I was playing with pypi.org because I got an email saying "We noticed that you're a maintainer for 1 project that is a member of the top 100 most downloaded from PyPI, and we would like to ask for your help testing the latest deployment of Warehouse." and decided to fix the things I found instead of reporting them. I noticed two of my PRs were already reported after I already fixed them. Feel free to close all of them.

**Comment by brainwane** [comment]
I'm sorry for misunderstanding, @berkerpeksag - I should have realized what you were doing there. Please disregard my comment as it was based on a false assumption.

**Comment by di** [comment]
On #3069, I said:

> I think I would prefer if this button was disabled w/ a tooltip, not hidden, as it might not be immediately obvious to a user why the button is present for some projects and not present for others.

@nlhkabu do you agree?

**Comment by nlhkabu** [comment]
Thanks for your PR @berkerpeksag - I agree with @di that  it would be better to disable this button and add a tooltip - would you be able to update your PR to follow this pattern?

**Comment by berkerpeksag** [comment]
Thank you for reviews, I will address your comments this weekend.

**Comment by nlhkabu** [comment]
Hi @berkerpeksag - after doing some user testing on this page, I think we should do the following:

1. Remove the 'view project' button completely
2. Make the *title* of the card link to the public page (if there is a release)

Would you be able to either update this PR to do this, or open a new one?

**Comment by berkerpeksag** [comment]
Thank you for your review, @nlhkabu. I hopefully addressed your comments in https://github.com/pypa/warehouse/pull/3073#issuecomment-372014843 correctly in PR #3257. Closing this one.

**Pull request closed without merging**
