### PR TITLE
Added ISO 8601 compliant upload time field to JSON API

### LINKED ISSUE #4751: JSON API omits timezone and microseconds from upload_time
When a request is made to `https://pypi.org/pypi/$PROJECT/json` or `https://pypi.org/pypi/$PROJECT/$VERSION/json`, the `"upload_time"` fields in the response contain no timezone information and has no sub-second precision (e.g., `"2018-09-22T19:16:05"`).  Compare this to the XML-RPC API, in which the `"upload_time"` fields in the data returned by the `release_urls` method all end with `Z` and have microsecond precision (e.g., `"2018-09-22T19:16:05.067954Z"`).

### PR DESCRIPTION
**Pull request by AWhetter**
Closes #4751

I'm not sure if `upload_time_iso_8601` is the best name for the field. It's descriptive at least...

This is an alternative to #4752, closes #4752.

### CODE REVIEW

**Comment by di** [comment]
I think this is probably the best solution to #4751.

Could you also add a `upload_time_iso_8601` field to the `release_urls` method of the XML-RPC API as well, just for consistency? (even though it will just have the same value)

**Comment by AWhetter** [comment]
Done! I've added the field to the XML-RPC API as well.

**Comment by di** [comment]
@AWhetter One last thing, let's also remove `upload_time` from the documentation.

**Comment by AWhetter** [comment]
Done!

**Pull request merged**
