### PR TITLE
Support uploading tuple of classifiers

### PR DESCRIPTION
**Pull request by gtback**
Added a failing test for #2185, and added a *potential* fix. I'm not a SQLAlchemy expert, so I expect there are likely better ways to fix it, but the test is (hopefully) useful regardless.

@gifforda helped me out with this.

### CODE REVIEW

**Comment by dstufft** [comment]
Hmm, I don't think this is going to fix #2185, because this is just modifying the test functions and not any of the actual code.

**Comment by gtback** [comment]
Yikes, I didn't realize that was just the test code until just now.

**Comment by dstufft** [comment]
No worries! FWIW I *think* the issue with #2185 might actually be client side? I haven't dig into it to figure it out, but I think that distutils/setuptools sends different content for tuple vs list there and I'm not sure why. It might be something we can work around in Warehouse though, I'm not sure.

**Comment by gtback** [comment]
I haven't used SQL Alchemy for anything non-trivial, but I would imagine there's some easy way for a Many-to-Many relationship to accept any iterable, rather than just a `list` (I just don't know what that is). It's possible that better client-side support would mitigate the bug, but Warehouse could also probably silently cast a tuple into a list. 

I tried adding `collection_class=list,` into [here](https://github.com/pypa/warehouse/blob/0d01a752790fbc04967d8355a49f754c6cf10acc/warehouse/packaging/models.py#L272), but that didn't seem to make a difference (at least in terms of the failing test), giving me `TypeError: Incompatible collection type: tuple is not list-like`.

**Comment by di** [comment]
Hey @gtback, thanks for taking a stab at this. Like Donald said, this looks like a distutils issue rather than an issue with Warehouse, so I'm going to close this PR.

If you're still interested in contributing to Warehouse, take a look at [these issues which are good for first-time contributors](https://github.com/pypa/warehouse/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).

**Comment by gtback** [comment]
Thanks, @di, and sorry I let this languish. The original approach didn't work, and I never spent the time to find a better one. I'll look for other issues to help out with. 😄

**Pull request closed without merging**
