### PR TITLE
Updated settings.html

### LINKED ISSUE #13143: Replace reference to `setup.py` in settings with `pyproject.toml`
This was originally identified in https://github.com/pypi/warehouse/pull/11985 but that PR was abandoned.

### PR DESCRIPTION
**Pull request by sabre-code**
Addressed issue mentioned  in this comment here https://github.com/pypi/warehouse/pull/11985#discussion_r939797816 @miketheman 
Please check if it's exactly the way you suggested. Thanks

Fixes #13143.
Closes #13299

### CODE REVIEW

**Comment by di** [comment]
Hi @sabre-code, thanks for the PR. For future reference, [you can link a pull request to it's issue using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword), like `fixes #13143` which will automatically cause the issue to be closed when the pull request is merged.

(I've gone ahead and done it for you here as well!)

**Comment by sabre-code** [comment]
Oh apologies for that and thanks.
It's my very first attempt to contributing on GitHub. So first merge as well. Will keep in mind next time. Thanks ❤️

**Comment by sabre-code** [comment]
> Hi @sabre-code, thanks for the PR. For future reference, [you can link a pull request to it's issue using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword), like `fixes #13143` which will automatically cause the issue to be closed when the pull request is merged.
> 
> (I've gone ahead and done it for you here as well!)

Just wanted to know whether the changes were as expected? as it shows here merging is blocked.

**Comment by di** [comment]
I also [updated the translation files](https://warehouse.pypa.io/development/submitting-patches.html#translations) for you as well, since this changes translated strings.

> Just wanted to know whether the changes were as expected? as it shows here merging is blocked.

Yes, this is because nobody has provided a review yet. I'll let @miketheman review as he was helping you in #11985.

**Review by miketheman — APPROVED** [review]
Thanks!

**Pull request merged**
