### PR TITLE
Documentation updates - Add UI principles and Glossary

### LINKED ISSUE #1275: Document naming standards
See #1252

### PR DESCRIPTION
**Pull request by nlhkabu**
Closes #1275.

### CODE REVIEW

**Comment by nlhkabu** [comment]
I can't work out why this linter is complaining... from my end the line length is fine :(

**Comment by dstufft** [comment]
I think it has to be ``<80`` not <=80``.

**Comment by nlhkabu** [comment]
Ok. I will update.  @dstufft any feedback on the content? I'm particularly concerned that I've got the terminology right...

**Comment by dstufft** [comment]
The content looks great to me.

**Pull request merged**
