### PR TITLE
Revert "Warehouse API currently redirects pypi.org/pypi/{project}/json/ (#3971)"

### LINKED ISSUE #4012: Redirect loop when requesting missing package
**Describe the bug**
When I `curl -v https://pypi.org/pypi/bogus/1.0.0/json` with an invalid package/version combination, I get put in an infinite redirect loop. If the package/version combination is correct, then the data is served as expected.

I noticed this because the `license_finder` gem just now started having issues when looking for my team's internal (non-PyPi) packages. Previously, it hadn't complained.

**Expected behavior**
For an invalid package/version combination, I'd expect a 404 (or whatever the previous behavior was).

**To Reproduce**
`curl -v https://pypi.org/pypi/bogus/1.0.0/json`, note that the `Location` header leads you to the same URL.

**My Platform**
Pretty sure my platform isn't relevant. I've reproduced the problem both from my personal internet connection as well as within AWS.

**Additional context**
Adding @dstufft @di as suggested on IRC.

### PR DESCRIPTION
**Pull request by di**
This reverts commit 464271b9676819e97348dd72646bad5dfe41d873.

Fixes #4012.

### CODE REVIEW

**Comment by dstufft** [comment]
Let's open an issue to re-fix the original issue now that it's reverted.

**Comment by di** [comment]
New issue for the original issue is here: #4016.

**Comment by jbergknoff-rival** [comment]
It seems like the Travis build is stalled. Any idea know when this change will land?

**Comment by di** [comment]
It might take a bit for this to get deployed to PyPI because there's currently a pretty long backlog in Travis due to all the PyPA development happening during the sprints.

**Pull request merged**
