### PR TITLE
register page - pyramids edition

### PR DESCRIPTION
**Pull request by toumorokoshi**
This is the pyramids edition of #334, or at least part of it.

In the interest of better feedback I'll be creating a series of smaller requests around implementing registration, rather than one giant one.

This is the UI portion of it: a simple interface that always returns a success.

### CODE REVIEW

**Comment by toumorokoshi** [comment]
I thought this would also be a good place to ask about actually adding the user: my current plan is to create a Pyramids service to handle reg interaction with the DB, and pass that into the RegisterForm like how the LoginForm works.

My question is: can I combine Reg + Login services into a UserLoginService? Or is it preferable to have them separate.

I kind of feel like having them be the same is a good grouping, functionality-wise, but I'm not married to either way (or some third way I should be implementing reg).

**Comment by dstufft** [comment]
I think it makes sense to have them in a single service, just rename ``LoginService`` to ``UserService`` or something. That way all of the user related stuff goes through a service and we can swap out services for in memory ones or whatever easily.

**Comment by dstufft** [comment]
Is this dependent on #508 now?

**Comment by toumorokoshi** [comment]
yes. Although I think I'll probably have to send one more pull request to do something to send a confirmation e-mail out, before this is complete. so I guess we should let this one sit and I'll pick it back uponce the other functionality exists.

**Comment by karan** [comment]
Is this ready to be merged?

**Comment by toumorokoshi** [comment]
Not yet, unfortunately. This is waiting on #508, more functionality is required.

**Comment by ismail-s** [comment]
@toumorokoshi #508 has been merged, so is this pull request ready to be merged?

**Comment by toumorokoshi** [comment]
@ismail-s sorry about that, this dropped on my radar. I haven't had a chance to tackle it all the way yet. I'll start taking a look again, but if someone else wants to take the reigns, they're welcome to.

**Comment by dstufft** [comment]
This is fixed now.

**Pull request closed without merging**
