### PR TITLE
Add recaptcha to login

### PR DESCRIPTION
**Pull request by demianbrecht**
This should address #707

### CODE REVIEW

**Comment by dstufft** [comment]
I don't think we want a captcha on every single login, that would be somewhat annoying I think. It would be better if it only required a captcha after N failed login attempts for that IP address or for that user in the last Y minutes (rolling).

It's also not a complete solution because we also have the basic auth which is used in automated systems, so we probably want the two systems to share attempt counters, and have it so that for basic auth if you get too many failed attempts it just rejects your login, and for regular auth it shows a captcha.

**Comment by demianbrecht** [comment]
Yep, missing basic auth throws a bit of a wrench into this for sure. Captcha doesn't help much in that scenario and I imagine that's the path that would most likely be targeted by attackers.

Per-IP is going to be an issue with IPv6 (noted [here](https://github.com/pypa/warehouse/issues/707#issuecomment-190015037)). Also, I'm not sure how fond I am of per-IP blocks on auth given it has the potential to DoS legitimate users. Is this approach one used in PyPI?

So, I'll keep what's done so far, but I'll also add global system, per user and potentially per-IP sliding windows that will either trigger recaptcha in the FE or lock out accounts in the BE.

Sound reasonable?

**Comment by dstufft** [comment]
Right now in PyPI we have separate counters for user and for IP address. I think it's probably OK to drop the per IP address if we replace it with a global threshold that starts to trigger a captcha for all logins if the global failed logins reach some sort of threshold. We would (probably?) ignore that in the basic auth, but that's OK because longer term I plan to deprecate the basic auth and move to something generated by the system with high entropy (API key, Client TLS Certificate? Something Else?!) that shouldn't be vulnerable to that and at that point the via-basic-auth bypass for the global failed logins should be closed.

**Comment by dstufft** [comment]
To be clear, I'd suggest that we *only* ignore the global threshold when authenticating with basic auth, the per user block should not be ignored.

**Comment by di** [comment]
#707 was fixed in #1530 so this can be closed.

Thanks for taking a shot at this @demianbrecht!

**Pull request closed without merging**
