### PR TITLE
Issue #9203 Disable mismatch warning when confirm password field is empty

### LINKED ISSUE #9203: Confirm password prompts warning before we start giving input to it.
image

From the above image we can see that confirm password starts prompting "Passwords do not match" but I think that it should start the prompt when we have given at least one character input.

### PR DESCRIPTION
**Pull request by usernameandme**
Fixes #9203.

### CODE REVIEW

**Comment by di** [comment]
Could you add a test for this here? https://github.com/pypa/warehouse/blob/main/tests/frontend/password_match_controller_test.js

**Comment by usernameandme** [comment]
I removed the checks in that test case because that is not the expected functionality. Tests pass locally now.

**Comment by di** [comment]
> I removed the checks in that test case because that is not the expected functionality. Tests pass locally now.

Could we update the test to explicitly check: when both fields are empty, when the first is empty, when the second is empty? Right now it's only testing when the second value is empty.

**Comment by usernameandme** [comment]
Makes sense. Updated.

**Comment by usernameandme** [comment]
@di Can you please review and confirm?

**Pull request merged**
