### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by msabramo**
Changes to make it possible to package up a warehouse development environment with Docker. This makes it much easier to get started with Warehouse development, because it bundles PostgreSQL, Redis, Elasticsearch and it has pre-built cffi and such.

I have a pre-built image at https://registry.hub.docker.com/u/msabramo/warehouse/

So one could run warehouse by doing:

- `docker pull msabramo/warehouse`
- `docker run -i -t -P msabramo/warehouse`

### CODE REVIEW

**Comment by msabramo** [comment]
It would be nice to have a data dump, as outlined in https://github.com/pypa/warehouse/issues/343, so the Docker container could come with some data and be a better demo.

**Comment by msabramo** [comment]
I realized that I used an old version of Elasticsearch; I'm going to try to update it to the newest version.

**Comment by msabramo** [comment]
Updated to use Elasticsearch 1.4.2

**Comment by msabramo** [comment]
Test failures are bogus and I think that they are resolved by #352 and #354.

**Comment by alex** [comment]
Running everythign in the same docker container doesn't seem like the right approach to me, it seems like you want to use something like [fig](http://www.fig.sh/) for this.

**Comment by msabramo** [comment]
Yeah, it's been a while since I've looked at fig. Maybe I'll look again.

I thought that everything in one Docker container would be the simplest thing to get a dev environment going. I definitely wasn't thinking that it would be used in production like this.

Though, IIRC, fig also targets dev environments so maybe I should look at it again.

**Comment by dstufft** [comment]
I'm going to close this, I've started porting Warehouse over to Pyramid to ease the concerns of the custom framework-ish thing I've got going on here. That work is on the pyramid branch inside this repository. As part of that I've set it up so that a development environment can be spun up inside of Docker containers using [fig](http://fig.sh/).

**Comment by msabramo** [comment]
Check out [Docker Compose](https://blog.docker.com/2015/02/announcing-docker-compose/) -- it's the next generation of fig.

**Comment by dstufft** [comment]
Open an issue to look at switching to that please!

**Comment by msabramo** [comment]
https://github.com/pypa/warehouse/issues/361

**Pull request closed without merging**
