### PR TITLE
Register Page / Registration Flow 

### PR DESCRIPTION
**Pull request by toumorokoshi**
Related to #322, this is a first draft at a registration page / registration flow. As of the initial pull request, it is the full workflow sans sending a confirmation e-mail, and and agreeing to a terms of use.

### CODE REVIEW

**Comment by dstufft** [comment]
I'm not going to close this, but I've started porting Warehouse over to Pyramid to ease the concerns of the custom framework-ish thing I've got going on here. That work is on the pyramid branch inside this repository. I'm leaving this open because I'm going to need to port this PR over to that new branch, and I want to be able to re-use the work done here.

**Comment by toumorokoshi** [comment]
@dstufft ok! Let me know if you want any help with that: I'm happy to spend some time to port it over.

**Comment by dstufft** [comment]
If you want to do that, that'd be great :) I wasn't going to ask that since my decision to switch is what invalidated this PR but if you're willing to do that, it'd be great!

**Comment by toumorokoshi** [comment]
Anything I can do to help Warehouse out there :) Just letting you know I'm going to start the work now. I don't have an ETA, but i'll start a pull request as soon as I have something.

**Comment by dstufft** [comment]
Awesome! If you need any help just let me know. Hopefully the new setup is easier to work on than before.

**Comment by dstufft** [comment]
@toumorokoshi is it helpful to you to have this Pull Request remain open while you work on getting register support into the Pyramid based Warehouse? If not I'll close it now that you're working on it.

**Comment by toumorokoshi** [comment]
Nope! Just wanted to let people know I'd like to tackle it, but I guess that's apparent now :)

**Pull request closed without merging**
