### PR TITLE
Add note about gravatars taking a while to update

### LINKED ISSUE #3086: Add note indicating that changing Gravatar images might take a while to appear
Because the user page is cached, if the user changes their Gravatar image, it might take a while before it actually shows up on their profile page.

We should add a note below the "Change Image on Gravatar.com" link informing users that they may not see the change right away.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

### PR DESCRIPTION
**Pull request by jonparrott**
Fixes #3086

### CODE REVIEW

**Comment by jonparrott** [comment]
Screenshots:

Old:

screen shot 2018-03-24 at 8 46 40 pm

New:

screen shot 2018-03-24 at 8 46 27 pm

**Comment by jonparrott** [comment]
I changed mine fairly recently and it took around 5 minutes. Gravatar sets
cache control headers.

**Comment by di** [comment]
Yeah, I think this isn't true anymore, but it shouldn't have taken five minutes, so let me investigate this.

**Comment by brainwane** [comment]
(Dustin may not be able to get to this till next week.)

**Comment by di** [comment]
I tested this. Warehouse purges the user page immediately, and will immediately show the current avatar for the new address (or none if there isn't one) so no problems on our end.

However if the user changes the avatar for a given email address, seems like it takes ~1 minute or so for Gravatar to update their response for the given URL to have the new image.

Since this would be expected anywhere Gravatar is used, and since the amount of wait time is far less than it was when I originally filed the issue, I'm going to just close this PR and the corresponding issue, and we can revisit if folks complain about this.

Thanks @jonparrott! (and sorry to waste your time a bit here).

**Comment by jonparrott** [comment]
No worries!

**Pull request closed without merging**
