### PR TITLE
Ensure Project.total_size is updated on Release removal

### LINKED ISSUE #8213: Project total_size is not updated when a release/file is removed
In https://github.com/pypa/pypi-support/issues/478 users are saying they have removed files/releases but this is not changing the `Project.total_size` for their project.

### PR DESCRIPTION
**Pull request by ewdurbin**
Previously this trigger was not being fired when Release objects were deleted.

It seems as though row level Postgres triggers are not fired on CASCADE'd deletes.

Resolves #8213

### CODE REVIEW

**Comment by ewdurbin** [comment]
CC: @DavidBord I think this makes sense based on your work but would appreciate your review as well.

**Comment by di** [comment]
Do we need to add a trigger on `projects` too, for when project deletion cascades to releases/release files?

**Comment by ewdurbin** [comment]
> Do we need to add a trigger on `projects` too, for when project deletion cascades to releases/release files?

Since we're storing Project total_size on the Project, we do not! We're deleting the row that contains the column in question.

**Comment by di** [comment]
It seems like we should probably also trigger a one-time recalculation of `total_size` for all projects, so users don't have to manually trigger this to get an updated/correct `total_size`.

**Comment by ewdurbin** [comment]
> It seems like we should probably also trigger a one-time recalculation of `total_size` for all projects, so users don't have to manually trigger this to get an updated/correct `total_size`.

It's in the migration :-D

**Comment by di** [comment]
> It's in the migration :-D

D'oh, missed that!

**Comment by ewdurbin** [comment]
> > It's in the migration :-D
> 
> D'oh, missed that!

2020, grace and patience abounds <3

**Comment by DavidBord** [comment]
@ewdurbin seems legit

**Pull request merged**
