### PR TITLE
Update links to distutils-sig from pypa-dev

### LINKED ISSUE #8012: Update mailing list link in developer docs
We've now [decommissioned](https://groups.google.com/d/msg/pypa-dev/rUNsfIbruHM/LCEx-CB5AgAJ) the [pypa-dev Google Group](https://groups.google.com/forum/#!forum/pypa-dev).

I'd like for someone to go through the following developer documentation pages and update all the following links so that they point to [https://mail.python.org/mailman3/lists/distutils-sig.python.org/](https://mail.python.org/mailman3/lists/distutils-sig.python.org/) instead.

This is a good first contribution for someone who's new to this repository. You open up the files listed below and change the URL on the following lines:

* `README.rst`, line 54:.```. _`pypa-dev mailing list`: https://groups.google.com/forum/#!forum/pypa-dev```
* `docs/development/getting-started.rst`, starting on line 26: ```- For longer-form questions or discussion, message the `pypa-dev mailing```
* `docs/development/getting-started.rst`, line 609: ```Freenode`_, or the `pypa-dev mailing list`_, to ask questions or get```
* `docs/development/getting-started.rst`, line 633: ```.. _`pypa-dev mailing list`: https://groups.google.com/forum/#!forum/pypa-dev```
* `docs/development/index.rst`, line 19: ```or the `pypa-dev mailing list`_, to ask questions or get involved.```
* `docs/development/index.rst`, line 38: ```.. _`pypa-dev mailing list`: https://groups.google.com/forum/#!forum/pypa-dev```

and then open a pull request.

This is a followup to #8010.

--

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [distutils-sig.python.org mailing list](https://mail.python.org/mailman3/lists/distutils-sig.python.org/).

### PR DESCRIPTION
**Pull request by arshadrr**
This PR replaces references to the decomissioned pypa-dev google group with the distutils-sig mailing list. Closes #8012 . Thanks @brainwane for the approachable first issue :)

### CODE REVIEW

**Comment by brainwane** [comment]
You're welcome, and congrats on making your first pull request ever! Am reviewing now.

**Comment by brainwane** [comment]
Thanks for writing a descriptive commit message. [Here's a guide to help you write commit messages](https://zulip.readthedocs.io/en/latest/contributing/version-control.html#commit-messages) that are more consistent with general commit message style style, which makes it easier for us in the future -- when someone's trying to solve a new problem, if commit messages are all in the same format, it's easier to skim them in logs and quickly understand what's happening.

[Here are some tips on tidying your commit history, including changing your commit messages.](https://zulip.readthedocs.io/en/latest/git-guide.html#examine-and-tidy-your-commit-history) And when you update your code or your commit message, you can [update your pull request](https://zulip.readthedocs.io/en/latest/git-guide.html#update-a-pull-request) and the changes will appear here. :)

**Comment by brainwane** [comment]
@arshadrr If you'd like a suggestion for your SECOND issue to work on, comment here and say so. :-) Thanks again.

**Comment by arshadrr** [comment]
@brainwane Sure, I'd like that.

**Comment by arshadrr** [comment]
@brainwane Oh, and I think the two links in the second paragraph of the comment you made about commit messages might have moved.

**Comment by brainwane** [comment]
Thanks for that heads-up. I need to update and fix my Saved Replies, clearly.

**Pull request merged**
