### PR TITLE
Support RTL locales

### LINKED ISSUE #6683: Support for properly displaying the site translated to RTL languages
**What's the problem this feature will solve?**
Display PyPI.org propely when translated to RTL languages such as Arabic, Farsi and Hebrew.

**Describe the solution you'd like**
I can't suggest a specific technical solution, since I'm not familiar with the website's design and implementation.

**Additional context**
The context is the recent work on translation into additional languages.

### PR DESCRIPTION
**Pull request by di**
This gets us most of the way to supporting RTL locales, but will probably need some specific tweaks from @nlhkabu.

This PR also enables Hebrew for testing RTL locales.

TODO:
- [x] Update tests
- [x] Update translations
- [x] ???

| LTR  | RTL | 
| - | - |
| Screen Shot 2020-05-11 at 3 44 06 PM  | Screen Shot 2020-05-11 at 3 49 14 PM |

Fixes #6683.

### CODE REVIEW

**Comment by di** [comment]
I saw this happen once locally and it also happened in CI here, seems flakey but would be nice to figure out how to avoid this, it's likely either due to `gulp-rtlcss` or `gulp-rename` or how we're using them.

```
bin/static_pipeline: line 12: 12215 Segmentation fault      (core dumped) gulp dist
```

**Comment by nlhkabu** [comment]
Rendering issues to address:

Content coming through from JS is not translated, and displays incorrectly:
Screenshot from 2020-05-14 22-20-12

--------------------

Timeago (?) JS plugin is messing with word order:
Screenshot from 2020-05-14 22-18-22

We should be able to correct this by setting the `time` element to ltr.

----------------
Error messages need to be checked.  Are none marked for translation? If so, icon needs adjustment, and EN needs to be set to ltr.

Screenshot from 2020-05-14 22-17-31

**Comment by di** [comment]
@nlhkabu Seems like some of that is due to https://github.com/pypa/warehouse/issues/6825, we might need to address that (at least partially) to fix those strings.

**Comment by nlhkabu** [comment]
@di - yep. I've put temporary CSS in place to display these correctly while we wait for these to be marked for translation.

I've opened https://github.com/pypa/warehouse/issues/7955 to address the JS issues.

I don't think we should let #7955 or #6825 block the merge of this PR :)

**Comment by di** [comment]
> I saw this happen once locally and it also happened in CI here, seems flakey but would be nice to figure out how to avoid this, it's likely either due to `gulp-rtlcss` or `gulp-rename` or how we're using them.
> 
> ```
> bin/static_pipeline: line 12: 12215 Segmentation fault      (core dumped) gulp dist
> ```

FWIW I'm also seeing these same segfaults on master (e.g. https://travis-ci.org/github/pypa/warehouse/jobs/688695161) so I don't think it's related to these RTL packages and figuring that out shouldn't block this PR.

**Comment by nlhkabu** [comment]
@taleinat I am almost done on the CSS tweaks I need to make on this PR.
Would you be able to pull down this branch and test that everything is rendering as it should.  I have added some items I am not sure about below:

## Translation incorrect?

Screenshot from 2020-05-24 15-45-42

For reference, here it is in English:
Screenshot from 2020-05-24 15-45-29

## File type and date

I assume "Wheel, 1 Source 1" should be "1 Wheel, 1 Source" as per the English version:

Screenshot from 2020-05-23 21-40-31

Can you also confirm that the dates here are rendering correctly?

## Code comments
Finally, are these code comments ok?
Screenshot from 2020-05-23 21-39-56

**Comment by taleinat** [comment]
> Would you be able to pull down this branch and test that everything is rendering as it should.

Unfortunately I don't have a good local Docker setup :/ I tried for quite a while to set things up when this PR was created, but ended up giving up. I'll see if I have a better way to try it.

**Comment by nlhkabu** [comment]
> Unfortunately I don't have a good local Docker setup :/ I tried for quite a while to set things up when this PR was created, but ended up giving up. I'll see if I have a better way to try it.
Ok, let me know if this isn't going to be possible - maybe we can instead work out a time to have a quick pairing session.

**Comment by taleinat** [comment]
> Translation incorrect?

The first translation appear to be missing a `setup()` somehow. I've tried fixing that now, please let me know whether it helped.

The second issue is indeed an LTR/RTL issue. Since the package types are not translated, I'd say the whole section in parentheses should have on override to make it LTR. (Alternatively, make the package types also translatable.)

The dates look great (in Israel we write, and say, the day of the month first), as do the code comments afterwards. :)

**Comment by taleinat** [comment]
> Ok, let me know if this isn't going to be possible - maybe we can instead work out a time to have a quick pairing session.

Oooh, yes, let's do that! Sounds like fun :)

**Comment by di** [comment]
OK, this should be good to go. Will merge tomorrow AM.

**Pull request merged**
