### PR TITLE
Integrate statuspage.io into footer

### LINKED ISSUE #604: Integrate statuspage.io
We'll want to integrate statuspage.io so that people can get a link to the status.python.org incidents when one is occuring. They have a web API that we are currently using via javascript on pypi.python.org.

See: https://status-page-blog.herokuapp.com/embed-system-status-within-your-webapp

### PR DESCRIPTION
**Pull request by berkerpeksag**
Fixes #604

### CODE REVIEW

**Comment by berkerpeksag** [comment]
Fixed test failure and linting issue.

**Comment by nlhkabu** [comment]
Looks great from my side.

**Comment by dstufft** [comment]
Reviewing this, I'd prefer it if we didn't bake the statuspage.io ID into the code here. I'd prefer it if instead it was made a setting. So you'd want to add a new setting to the list in ``warehouse/config.py`` and then read that setting in ``warehouse/csp.py``.

For passing that data into javascript, you'd then do something like:

```
{% if request.registry.settings.get("statuspage.domain") $}
<li><a href="https://status.python.org/">Status: <span data-statuspage-domain="{{ request.registry.settings['statuspage.domain'] }}">All Systems Operational</span></a></li>
{% endif %}
```

Then you could adjust the JS to pull this data out of this using something like what was doing for HTML including in ``warehouse/static/js/warehouse/utils/html-include.js``.

**Comment by berkerpeksag** [comment]
Thanks for the idea. I have just implemented it.

**Comment by berkerpeksag** [comment]
Fixed the merge conflict.

**Pull request merged**
