### PR TITLE
Log celery errors for Sentry

### LINKED ISSUE #1112: Errors in celery don't get sent to Sentry

### PR DESCRIPTION
**Pull request by di**
This is the patch from #1167 with tests added. Fixes #1112.

I can't actually verify that this works, mind taking a look @dstufft?

### CODE REVIEW

**Comment by dstufft** [comment]
I'll have to poke this a bit tomorrow, thanks!

**Comment by dstufft** [comment]
Ok, finally got a chance to take a look at this (sorry!).

I think this looks mostly right, except that I'm not sure what the effect would be on calling this unconditionally in the ``includeme``, which will get used during non-celery code too. The Raven docs suggest using the ``on_configure`` hook of Celery to "encapsulate behavior". So I think we should move this to that?

I think all it should need to do is move the two lines of code over to [warehouse/celery.py#L28-L30](https://github.com/pypa/warehouse/blob/d57186c3b5f783e2235b7d5be610302adce23c6f/warehouse/celery.py#L28-L30) and make it look something like:

```python
@celeryd_init.connect
def _configure_celery(*args, **kwargs):
    config = configure()
    celery.register_logger_signal(config.registry["raven.client"])
    celery.register_signal(config.registry["raven.client"])
```

I'll try to take a poke at doing that and seeing if it works unless you feel like refactoring and beat me to it.

**Comment by di** [comment]
@dstufft Thanks! I updated this PR.

**Comment by dstufft** [comment]
Awesome, thanks!

**Pull request merged**
