### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/pypa/warehouse/) for pypa/warehouse.

### CODE REVIEW

**Comment by webknjaz** [comment]
@di mind merging so that we could see how the recent translations are getting rendered.

P.S. This commit message looks weird https://github.com/pypa/warehouse/pull/7787/commits/87e19ac62deacbc4cf67bae486c100985c13c5ea — does Weblate have a bug on their side?

**Comment by fitojb** [comment]
> does Weblate have a bug on their side?

I believe each project manager can customize how they want Weblate to word its commits.

**Comment by webknjaz** [comment]
I mean, the title shouldn't be `Co-Authored-By`

**Comment by webknjaz** [comment]
@ewdurbin ^

**Comment by di** [comment]
We're aware, thanks.

**Comment by webknjaz** [comment]
@di what's blocking this? Many languages could go live like a month ago. But currently, new and changed strings are still shown in English.

**Comment by di** [comment]
@webknjaz We don't have a way to preserve attribution here _and_ squash commits due to how Weblate's squash addon works. I'm working on improving it but it hasn't been high-priority right now.

**Comment by webknjaz** [comment]
@di yeah, I understand. But it'd be great if you could just merge this manually. I'm more concerned about the completed translation that doesn't hit the production for a long time.

**Comment by di** [comment]
Merging this so we can test Hebrew translations.

**Pull request merged**
