### PR TITLE
Missing verified email url

### PR DESCRIPTION
**Pull request by saxenanurag**
Change the hard coded pypi url with the pyramid `route_url` method. Fix for #3184

### CODE REVIEW

**Comment by brainwane** [comment]
Thank you @saxenanurag!

Thanks for writing a descriptive commit message. It would be great if your commit message were a bit more descriptive -- https://zulip.readthedocs.io/en/latest/version-control.html#commit-messages is a good guide (from a different project) to writing commit messages that make it easier to understand what a commit is doing. (A clear commit message also makes debugging in the future easier -- when someone's trying to solve a new problem, if commit messages are all in the same format, it's easier to skim them in logs and quickly understand what's happening.)

[Here are some tips on tidying your commit history, including changing your commit messages.](https://zulip.readthedocs.io/en/latest/git-guide.html#examine-and-tidy-your-commit-history) And when you update your code or your commit message, you can [update your pull request](https://zulip.readthedocs.io/en/latest/git-guide.html#update-a-pull-request) and the changes will appear here. :)

And you don't need to close the old one and open a new one. You can [update your pull request](https://zulip.readthedocs.io/en/latest/git-guide.html#update-a-pull-request) and we recommend you do that (instead of closing the old PR and opening a new one) because then it's easier to see the history of what you've done, to to check that you've responded to previous reviewers' comments, and to preserve links we've mentioned (in comments) with other issues and PRs.

Sorry if any of this is redundant! If you have questions, please feel free to ask them here, in [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or on the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by saxenanurag** [comment]
Thank you so much @brainwane !

I will make the changes and push changes.

**Comment by brainwane** [comment]
Looking forward to it. Thanks, @saxenanurag.

**Comment by brainwane** [comment]
@saxenanurag I'm going to close this and ask you to concentrate on one pull request at a time, at least for now -- concentrate on #3405, and then when that's done, let's have you work on another issue. Thanks!

**Pull request closed without merging**
