### PR TITLE
Add webauthn beta badge

### LINKED ISSUE #5976: "beta" badge for WebAuthn beta feature within Account Settings
**What's the problem this feature will solve?**
The new WebAuthn two-factor auth method is going to -- initially -- be in beta, and we want to alert users to that when letting them use it.

**Describe the solution you'd like**
For the WebAuthn rollout, @ewdurbin suggested that we initially add a _badge_ in the Account Settings marking the WebAuthn 2FA method as "beta". This badge should be on the same line as the WebAuthn entry (and clearly NOT apply to the TOTP method) and should probably link to an FAQ entry or GitHub issue or [wiki page](https://wiki.python.org/psf/WarehousePackageMaintainerTesting) about the beta.

**Additional context**
Because we don't have #5869 yet.

### PR DESCRIPTION
**Pull request by nlhkabu**
Closes #5976 

To be merged after #5795. I have made this as a separate PR, so that we can easily revert to remove the badges :)

## Screenshots

Screenshot from 2019-06-08 11-12-06
Screenshot from 2019-06-08 11-14-43
Screenshot from 2019-06-08 11-12-49
Screenshot from 2019-06-08 11-12-42

@brainwane as per your issue, did you want me to link through to [here](https://wiki.python.org/psf/WarehousePackageMaintainerTesting), or are we planning to add a FAQ?

### CODE REVIEW

**Comment by brainwane** [comment]
> @brainwane as per your issue, did you want me to link through to [here](https://wiki.python.org/psf/WarehousePackageMaintainerTesting), or are we planning to add a FAQ?

@nlhkabu Good question. I think we should add a "what are beta features?" FAQ item. And then we can update that FAQ with "here are the current beta features" and provide appropriate hyperlinks -- in the case of WebAuthn I need to update https://wiki.python.org/psf/WarehousePackageMaintainerTesting to give context and suggest how to test it.

**Comment by brainwane** [comment]
@nlhkabu

Here's a quick draft of an FAQ item:

> Q: What does the "beta" badge mean? What are Warehouse's current beta features?

> A. While Warehouse's maintainers are deploying new features, at first we mark them with a small "beta" symbol to tell you: this should probably work fine, but it's new and less tested than other site functionality. Right now our beta features are:

> * In your Account Settings: [WebAuthn (U2F key) support for two-factor authentication](https://wiki.python.org/psf/WarehousePackageMaintainerTesting), rolled out as beta 11 June 2019.

I updated https://wiki.python.org/psf/WarehousePackageMaintainerTesting enough that it would be fine to link to in an FAQ.

**Comment by nlhkabu** [comment]
Updated to work with new UI and FAQ:

Screenshot from 2019-06-13 07-14-44

Screenshot from 2019-06-13 07-13-51

**Comment by ewdurbin** [comment]
replaced with #6027, the merge situation got a bit too wild for me to unwind.

**Pull request closed without merging**
