### PR TITLE
Project Settings / Delete Project

### LINKED ISSUE #2805: Enable deleting a project
A sub ticket of #424

We need to enable deleting a project via the manager admin.

I have created the UI for this in `warehouse/templates/manage/project.html`

screenshot from 2018-01-17 06-56-39

screenshot from 2018-01-17 06-56-47

The code for this is currently commented out.

We need to:

- Uncomment the relevant html sections
- Make the delete form (in modal) work, including the 'show password' functionality
- Add a redirect (to the projects page?), that includes a confirmation message to tell the user their project has been deleted successfully.

### PR DESCRIPTION
**Pull request by di**
Fixes #2805. This moves the releases to their own route, and stubs out an "options" page with a basic form for project deletion.

(cc @nlhkabu)

### CODE REVIEW

**Comment by nlhkabu** [comment]
Awesome, thanks @di!
I will pull it down and take a look :)

**Comment by nlhkabu** [comment]
Hi @di, I've pushed up some changes in light of the new structure.

I've noticed that I'm getting an error on the collaborators page:

screenshot from 2018-01-23 06-57-31

Could you please take a look.

This is almost ready to merge on my side - I just need to look at the mobile UI.

**Comment by di** [comment]
@nlhkabu Sorry about that, fixed now!

**Comment by nlhkabu** [comment]
Thanks @di - I'll fix the rest of the UI tomorrow, so hopefully we can merge :)

**Comment by nlhkabu** [comment]
This page is now done from a style POV on both mobile and desktop:

screenshot from 2018-01-26 07-33-23
fireshot capture 9 - manage opstacle setting_ - http___localhost_manage_project_opstacle_settings_
screenshot from 2018-01-26 07-33-05

Still a bit ugly on mobile:

- Projects page (list of projects)
- Releases table
- Collaborators table

I suggest we merge this PR and I can open a new one to address these, as well as #2838 

What do you think @di?

**Comment by nlhkabu** [comment]
Ok, rebased with master, so we should be ready to go :grin: 

One thing I noticed in the templates:

```html
<div class="package-snippet__buttons">
  <a href="{{ request.route_path('manage.project.releases', project_name=project.normalized_name) }}" class="button button--primary">Edit</a>
  <a href="{{ request.route_path('packaging.project', name=project.normalized_name) }}" class="button">View</a>
</div>
```

Is there a good reason why one is `project_name=blah` while the other is `project=blah` ?

**Comment by di** [comment]
> I suggest we merge this PR and I can open a new one to address these, as well as #2838

Sounds fine to me!

> Is there a good reason why one is `project_name=blah` while the other is `project=blah` ?

Yeah, I changed all of the `manage` routes to take a `project_name` instead so I can reuse the `confirm_project` and `delete_project` utility functions that we already have on the admin side of things. All the admin routes took a `project_name` instead of just `name` and I figured that the former was less ambiguous.

It's probably worth updating all the `packaging` routes to take a `project_name` instead as well, but since it's not really necessary for this PR, I left it for later.

**Comment by di** [comment]
I made a small tweak here to match the new "Edit Project" button, which is that "Project Settings" is the first item in the menu, and the default when you press the "Edit" button on the list of projects.

We should fix #2418 (via #2849) before merging this, so that deleting a project purges the cache.

**Comment by nlhkabu** [comment]
Hi @di - I agree that the 'edit' button should go to the same place, but I'm not sure that I agree that the 'settings' page is the best landing page?

At the moment the only thing on there is to delete a project, which we want to "hide" as much as possible in the UI.

What is the most common action a project owner/maintainer will want to do?  Look at / edit their releases, manage their collaborators, or change the settings?  Maybe we can get this information from the current site analytics?

**Comment by di** [comment]
@nlhkabu Great point. I changed this back to make the "releases" page the default, and we can reevaluate the ordering later if need be.

**Comment by nlhkabu** [comment]
giphy-downsized 3

**Pull request merged**
