### PR TITLE
Make color scheme WCAG 2.0 AA compliant

### LINKED ISSUE #3334: insufficient contrast in PyPI colours
From #2417:

> I like the `pip install xx` in the header, but because of the background color it doesn't really stand out and is easy to miss. I would suggest a more contrasting color?

Marking `accessibility` in case we aren't hitting a11y standards for contrast.

### PR DESCRIPTION
**Pull request by nlhkabu**
Closes #3334 

Includes code highlighting scheme:

screenshot from 2018-04-04 20-59-39

Note: this updates makes the Warehouse color scheme AA compliant, not *AAA* compliant.

### CODE REVIEW

**Comment by nlhkabu** [comment]
@lgh2 would you have time to review this?  If not, I can ask someone else :) thanks

**Comment by nlhkabu** [comment]
:man_dancing: :man_dancing: :man_dancing: :man_dancing: :man_dancing:

**Comment by lgh2** [comment]
I'm sorry, @nlhkabu - I have been sick the last few days - I can still review this if you would like.

**Comment by nlhkabu** [comment]
no problem @lgh2 :) No need to re-review, but I might ping you on some others if that is ok?

**Pull request merged**
