### PR TITLE
Use 'Released' instead of 'Last released' because it's used for older releases too

### LINKED ISSUE #7015: Wording: says "Last released:" for old releases
**Describe the bug**

Might not be a bug, more of a language suggestion.

It says, for example, "Last released: Aug 31, 2010" for old releases.

**Expected behavior**

It's a little bit confusing to see "Last released:" when talking about an old release.

Is it possible for an old release to be released again at a later date?

Should it only say "Last released:" for the current release and "Released:" for older ones?

Or just say "Released:" for all releases?

**To Reproduce**

1. Visit https://pypi.org/project/numpy/
-> "Last released: Nov 11, 2019"
2. Visit an older release: https://pypi.org/project/numpy/1.5.0/
-> "Last released: Aug 31, 2010"

**My Platform**

n/a

**Additional context**

n/a

### PR DESCRIPTION
**Pull request by hugovk**
Fixes #7015.

Is there a way to ping the translators?

### CODE REVIEW

**Comment by di** [comment]
I think we might need to update our docs with regards to translations. You shouldn't edit the `.po` files, this is done by our translation service. You should just update the relevant string and run `make compile-pot` to rebuild the `.pot` file used to collect all translatable strings.

I tried to push this change to your branch but looks like your fork doesn't allow edits from maintainers.

**Comment by hugovk** [comment]
Hmm, there's no checkbox to "allow edits from maintainers".

Thanks for the info, will update when back at a keyboard (or you can PR to my fork).

**Comment by hugovk** [comment]
Rebased on master and ran `make compile-pot`, which only modified the `POT-Creation-Date`.

**Comment by di** [comment]
Thanks!

**Pull request merged**
