### PR TITLE
Autofocus search field

### PR DESCRIPTION
**Pull request by techtonik**

### CODE REVIEW

**Comment by di** [comment]
Lots of discussion about this in #854 and #3440.

**Comment by techtonik** [comment]
@nlhkabu can you confirm that `autofocus` on mobile causes keyboard popup? I would appreciate a prooflink, because it sounds like a bug rather than expected behavior for HTML5 element. Also @di previous patch didn't use HTML5, but JavaScipt - https://github.com/nlhkabu/warehouse/commit/0d45556a2ed10c27d4ed677cfaf14fb9f3bf42c5 so I think it should be safe.

@dstufft already merged HTML5 fix in https://github.com/pypa/warehouse/pull/985 but I don't see why it was reverted.

**Comment by techtonik** [comment]
The only argument that is left is accessibility of the top menu. While accessibility touches the focus issue, I think that Accessibility should be addressed site-wide with PSF funding, which could result in proper coverage and development and guidelines for contributors.

**Comment by di** [comment]
> @dstufft already merged HTML5 fix in #985 but I don't see why it was reverted.

@nlhkabu removed it in https://github.com/pypa/warehouse/pull/2822, though I'm not sure why.

**Comment by di** [comment]
@nlhkabu Can you merge/close this issue as you see fit?

**Comment by nlhkabu** [comment]
Hi @techtonik thanks for this PR

Thanks to the recent OTF funding for accessibility, I've had time to look into the issue of *whether* or not this is a good idea. I've opened a ticket with my findings here: #6088

TLDR: Based on the available accessibility recommendations, and the data that shows how users are using the page, we should not focus the search box.

Thanks again for your PR.

**Comment by techtonik** [comment]
@nlhkabu I can not comment on your research in #6088, because comments are locked.

Am I reading your results right?

 - 52.9% use search after landing
 - 8.5% do something else
 - 38.6% people bounce and leave the site

If that is so, that means that 84.5% of site users are doing search, which also means its the primary site function for the 84.5% of users. Do they do extra clicking? Or sole keyboard navigation?

**Pull request closed without merging**
