### PR TITLE
GNU Terry Pratchett

### PR DESCRIPTION
**Pull request by ncoghlan**
http://www.gnuterrypratchett.com/

### CODE REVIEW

**Comment by dstufft** [comment]
The change looks good to me, it's going to fail tests though. You'll need to add a ``pretend.call(...)`` here: https://github.com/pypa/warehouse/blob/master/tests/test_config.py#L178-L180 and you'll need to test the actual tween itself (same file, there's tests for the CSP tween there, should be pretty simple).

**Comment by dstufft** [comment]
Also you'll want to run ``tox -e pep8`` to make sure it passes that.

**Comment by ncoghlan** [comment]
Ah, the we learned so much about writing web services between the dawn of PyPI v1 and the dawn of Warehouse :)

**Comment by dstufft** [comment]
Tests for great justice :D Wouldn't want a regression in the ``X-Clacks-Overhead: GNU Terry Pratchett`` header after all!

**Comment by dstufft** [comment]
It might make sense to just close this since https://github.com/python/psf-salt/pull/41 exists now. I intend for Warehouse to be deployed behind the PSF LBs.

**Comment by ncoghlan** [comment]
Heh, I just came here to close this on that basis :)

**Pull request closed without merging**
