### PR TITLE
When search results >10,000 hits indicate with +

### PR DESCRIPTION
**Pull request by cryvate**
This fixes issue #3161 .

### CODE REVIEW

**Comment by cryvate** [comment]
Does this require testing, how would I test this?

**Comment by nlhkabu** [comment]
Thanks @cryvate!

I *don't* think we'd require a test for this - ping @di for feedback :)

**Comment by dstufft** [comment]
Nah, there's no real way to test this change.

**Comment by nlhkabu** [comment]
Thanks for this PR @cryvate :)

I've just closed the associated issue.

A small tip for next time: you can [use a keyword in your PR](https://help.github.com/articles/closing-issues-using-keywords/) (e.g. "Closes #issuenumber) and GitHub will automatically close the associated issue :)

Given this ticket was pretty small, feel free to pick up any other ticket marked with 'good first ticket' - we'd love to see another PR from you!

**Pull request merged**
