### PR TITLE
Update main.in

### PR DESCRIPTION
**Pull request by Manthan03583**

### CODE REVIEW

**Comment by ewdurbin** [comment]
Hi @Manthan03583, can you explain more about what you're attempting to do with this change? This file is not intended to be interpreted by Python.

**Comment by Manthan03583** [comment]
> Hi @Manthan03583, can you explain more about what you're attempting to do with this change? This file is not intended to be interpreted by Python.

I am just trying do this with python

**Comment by di** [comment]
Looks like this is trying to fix #8299, is that correct?

**Comment by ewdurbin** [comment]
Documentation on adding new dependencies (which is effectively the same as declaring one explicitly) is available at https://warehouse.pypa.io/development/patterns/#adding-new-dependencies

**Comment by eamanu** [comment]
Hi! yes this PR seems to be a fix of #8299. Do you need some help @Manthan03583

**Comment by Manthan03583** [comment]
> Looks like this is trying to fix #8299, is that correct?

**Pull request closed without merging**
