### PR TITLE
Change public info

### LINKED ISSUE #2829: Manage Account: Change public information
From #423: From the 'manage account' page, a logged-in user should be able to change the following information displayed on their "public" profile:

* Gravatar image (display the image and provide a link to gravatar to change it)
* Name

### PR DESCRIPTION
**Pull request by di**
Fixes #2829.

@nlhkabu This will need some styling, I was hoping that the gravatar image could be placed to the right of the form.

Also, I think we need to adjust the size of the user's real name on the profile page. A `h2` looks nice to me:

| screen shot 2018-01-23 at 3 24 48 pm | screen shot 2018-01-23 at 3 25 18 pm |
|-|-|

### CODE REVIEW

**Comment by nlhkabu** [comment]
thanks for this PR @di :)

Updated UI (tested on desktop and mobile):

screenshot from 2018-01-27 11-09-26

It would be great if we could tailor the gravatar message based on whether the user has an account or not.  I've added some commented out HTML:

```html
<!-- if gravatar account -->
<a href="{{ gravatar_profile(user.email) }}" target="_blank" class="button">
  Change image on gravatar.com
  <i class="fa fa-external-link" aria-hidden="true"></i>
  <span class="sr-only">Opens in new window</span>
</a>
<!-- else
<a href="https://gravatar.com/" target="_blank" class="button">
  Create an avatar on gravatar.com
  <i class="fa fa-external-link" aria-hidden="true"></i>
  <span class="sr-only">Opens in new window</span>
</a>
endif -->
```

Is this technically possible?

Another thing I noticed - we don't have an issue for editing a user's username?  Is there a reason we don't offer this?  If so, I think we should still display the username here somewhere. wdyt?

**Comment by nlhkabu** [comment]
hi @di, I have restyled the public profile page:

## Desktop
screenshot from 2018-01-29 07-49-46

## Tablet
screenshot from 2018-01-29 07-49-56

## Mobile
screenshot from 2018-01-29 07-50-06

I added an edit button for when the profile is the same as the logged in user:

```
<!-- if this user is logged in -->
  <a href="{{ request.route_path('manage.profile') }}" class="button button--primary author-profile__edit-button">Edit Profile</a>
<!-- endif -->
```

Could we please do the same with this as we did with the 'edit project' button?

**Comment by nlhkabu** [comment]
> I don't think this is possible -- all we can do is generate the URL to the image.

Ok, so let me remove my pseudo code in the template :)

> This isn't currently a feature of legacy. I don't really see any reason why it wouldn't be possible, but since it's a new feature it should probably wait until post-launch.

Yep, I 100% agree. However, I think we can*display* the username on this page in the short term - it seems odd that the user can't at least see it here.

> Yup, we can do this
\o/

**Comment by nlhkabu** [comment]
@di, I've pushed up a couple of changes - over to you :)

**Comment by di** [comment]
@nlhkabu I think I'm good here. I made a small tweak to display the user's primary email address used for the Gravatar image:

screen shot 2018-01-31 at 11 42 16 am

Also, I opted to hide the "full name" if it's empty on the public profile, rather than have it fall back on the username. I think it's confusing to the user that this would sometimes be their full name, and sometimes be their username.

Without the header, there's not enough padding between the image and the metadata, so you might need to add a small tweak here:

screen shot 2018-01-31 at 11 48 58 am

Other than that, I think this is good to go.

**Comment by nlhkabu** [comment]
## Profile with and without name

screenshot from 2018-01-31 20-18-23
screenshot from 2018-01-31 20-18-04

**Pull request merged**
